#!/usr/bin/env python3
"""Reproduce the selected equality rewrite and its final stopping trial.

Uses a fixed template to keep the measured caller shape stable. It never edits
production Solidity or existing generated variants. The library's external
packing and full preparation oracle remain in BabyBearEqFollowup.t.sol.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.28;\n// Generated by script/babybear/eq_followup_generate.py.\n// Equality uses 2*(a-1/2)*(q-1/2)+1/2. Canonical coefficient forms persist\n// across the accumulator chain. See testdata/babybear/followup-eq/bounds.md.\nimport { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";\nimport { BabyBearBenchField } from "./BabyBearSelectVariants.sol";\nimport { BabyBearPackedField, KoalaBearPackedField } from "./BabyBearPackedFields.sol";\n'
TEMPLATE = r'''
library @NAME@ {
    function _eqForms(uint256 acc, uint256[4] memory cache) internal pure returns (uint256 outLow,uint256 outRev) {
        assembly ("memory-safe") {
            let M := @MODULUS@
            let mask := 0xffffffff

            let low
            let high
            let c4
            {
                let a0 := mod(add(shr(224,acc),shr(1,M)),M)
                let a1 := and(shr(192, acc), mask)
                let a2 := and(shr(160, acc), mask)
                let a3 := and(shr(128, acc), mask)
                let a4 := and(shr(96, acc), mask)
                let bLow := mload(cache)
                let aLow := or(or(a0, shl(64, a1)), or(shl(128, a2), shl(192, a3)))
                c4 := add(shr(192,mul(aLow,mload(add(cache,32)))),mul(a4,and(bLow,0xffffffff)))
                low := mul(aLow,bLow)
                high := mul(or(or(a4,shl(64,a3)),or(shl(128,a2),shl(192,a1))),mload(add(cache,64)))
            }
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(shl(1,@R0@),add(shr(1,M),1)),M)
            let o1 := mod(shl(1,@R1@),M)
            let o2 := mod(shl(1,@R2@),M)
            let o3 := mod(shl(1,@R3@),M)
            let o4 := mod(shl(1,@R4@),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        }
    }
    function _mulForms(uint256 aLow,uint256 aRev,uint256 bLow,uint256 bRev) internal pure returns (uint256 outLow,uint256 outRev) {
        assembly ("memory-safe") {
            let M := @MODULUS@
            let mask := 0xffffffff

            let low := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(@R0@,M)
            let o1 := mod(@R1@,M)
            let o2 := mod(@R2@,M)
            let o3 := mod(@R3@,M)
            let o4 := mod(@R4@,M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        }
    }
    function _eqCached(uint256 a,uint256[4] memory cache) internal pure returns(uint256 out) {
        (uint256 low,uint256 rev)=_eqForms(a,cache);
        assembly ("memory-safe") { out := or(or(or(shl(224, and(low,0xffffffff)), shl(192, and(shr(64,low),0xffffffff))), or(shl(160, and(shr(128,low),0xffffffff)), shl(128, shr(192,low)))), shl(96, and(rev,0xffffffff))) }
    }
    function _stateAt(uint256[10] memory state,uint256 index) private pure returns(uint256 ptr) {
        assembly ("memory-safe") {ptr := add(state,shl(6,index))}
    }
    function _initialEqAt(uint256 ptr,uint256 a,uint256[4] memory cache) private pure {
        (uint256 low,uint256 rev)=_eqForms(a,cache);
        assembly ("memory-safe") {mstore(ptr,low) mstore(add(ptr,32),rev)}
    }
    function _accEqAt(uint256 ptr,uint256 a,uint256[4] memory cache) private pure {
        (uint256 low,uint256 rev)=_eqForms(a,cache);
        uint256 aLow;uint256 aRev;
        assembly ("memory-safe") {aLow := mload(ptr) aRev := mload(add(ptr,32))}
        (low,rev)=_mulForms(aLow,aRev,low,rev);
        assembly ("memory-safe") {mstore(ptr,low) mstore(add(ptr,32),rev)}
    }
    function _packAt(uint256 ptr) private pure returns(uint256) {
        uint256 low;uint256 rev;
        assembly ("memory-safe") {low := mload(ptr) rev := mload(add(ptr,32))}
        return _packForms(low,rev);
    }



    function _prepare(uint256 q,uint256[4] memory cache) internal pure {
        assembly ("memory-safe") {
            let M := @MODULUS@
            let q0 := and(shr(224,q),0xffffffff)
            let q1 := and(shr(192,q),0xffffffff)
            let q2 := and(shr(160,q),0xffffffff)
            let q3 := and(shr(128,q),0xffffffff)
            let q4 := and(shr(96,q),0xffffffff)
            q0 := mod(add(q0,shr(1,M)),M)
            let low := or(or(q0,shl(64,q1)),or(shl(128,q2),shl(192,q3)))
            mstore(cache,low)
            mstore(add(cache,32),or(shr(64,low),shl(192,q4)))
            mstore(add(cache,64),or(or(q4,shl(64,q3)),or(shl(128,q2),shl(192,q1))))
        }
    }
    function _eqTerm(uint256 a,uint256 b) internal pure returns(uint256) {uint256[4] memory cache;_prepare(b,cache);return _eqCached(a,cache);}
    function _packForms(uint256 low,uint256 rev) private pure returns(uint256 out) {assembly ("memory-safe") {out := or(or(or(shl(224, and(low,0xffffffff)), shl(192, and(shr(64,low),0xffffffff))), or(shl(160, and(shr(128,low),0xffffffff)), shl(128, shr(192,low)))), shl(96, and(rev,0xffffffff)))}}
    function _evaluateFixedEqTermsBlobRaw(
        bytes calldata blob,
        uint256 statementPointOffset,
        uint256 initialOodPoint,
        uint256 round0OodPoint,
        uint256 round1OodPoint,
        uint256 round2OodPoint,
        uint256[] memory fullPoint
    )
        internal
        pure
        returns (
            uint256 statementEq,
            uint256 initialEq,
            uint256 round0Eq,
            uint256 round1Eq,
            uint256 round2Eq
        )
    {






        uint256 initialCurrent = initialOodPoint;
        uint256 round0Current = round0OodPoint;
        uint256 round1Current = round1OodPoint;
        uint256 round2Current = round2OodPoint;
        uint256 pointBase;
        uint256[10] memory state;
        uint256[4] memory cache;
        assembly ("memory-safe") {
            pointBase := add(fullPoint, 0x20)
        }

        unchecked {
            {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    q := mload(add(pointBase, 672))
                    statementPointValue := and(
                        calldataload(add(add(blob.offset, statementPointOffset), 420)),
                        not(sub(shl(96, 1), 1))
                    )
                }
                _prepare(q,cache);
                _initialEqAt(_stateAt(state,0),statementPointValue,cache);
                _initialEqAt(_stateAt(state,1),initialCurrent,cache);
                _initialEqAt(_stateAt(state,2),round0Current,cache);
                _initialEqAt(_stateAt(state,3),round1Current,cache);
                _initialEqAt(_stateAt(state,4),round2Current,cache);
                initialCurrent = @FIELD@.square(initialCurrent);
                round0Current = @FIELD@.square(round0Current);
                round1Current = @FIELD@.square(round1Current);
                round2Current = @FIELD@.square(round2Current);
            }
            for (uint256 i = 21; i > 0; --i) {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    let idx := sub(i, 1)
                    q := mload(add(pointBase, shl(5, idx)))
                    statementPointValue := and(
                        calldataload(add(add(blob.offset, statementPointOffset), mul(20, idx))),
                        not(sub(shl(96, 1), 1))
                    )
                }

                _prepare(q,cache);
                _accEqAt(_stateAt(state,0),statementPointValue,cache);
                _accEqAt(_stateAt(state,1),initialCurrent,cache);
                initialCurrent = @FIELD@.square(initialCurrent);

                if (i > 4) {
                    _accEqAt(_stateAt(state,2),round0Current,cache);
                    round0Current = @FIELD@.square(round0Current);
                    if (i > 8) {
                        _accEqAt(_stateAt(state,3),round1Current,cache);
                        round1Current = @FIELD@.square(round1Current);
                        if (i > 12) {
                            _accEqAt(_stateAt(state,4),round2Current,cache);
                            round2Current = @FIELD@.square(round2Current);
                        }
                    }
                }
            }
        }
        statementEq = _packAt(_stateAt(state,0));
        initialEq = _packAt(_stateAt(state,1));
        round0Eq = _packAt(_stateAt(state,2));
        round1Eq = _packAt(_stateAt(state,3));
        round2Eq = _packAt(_stateAt(state,4));
    }
}
contract @NAME@Harness {
    function mul(uint256 a, uint256 b) external pure returns (uint256) {
        return @PACKED@.mul(a, b);
    }

    function square(uint256 a) external pure returns (uint256) {
        return @FIELD@.square(a);
    }

    function eq(uint256 a, uint256 b) external pure returns (uint256) {
        return @NAME@._eqTerm(a, b);
    }

    function squares(uint256 a, uint256 n) external view returns (uint256 used, uint256 result) {
        uint256 start = gasleft();
        result = a;
        for (uint256 i; i < n; ++i) {
            result = @FIELD@.square(result);
        }
        used = start - gasleft();
    }

    function prepare(bytes calldata statement, uint256[4] memory ood, uint256[] memory point)
        external
        view
        returns (uint256 used, uint256[5] memory result)
    {
        require(statement.length == 440 && point.length == 22, "SHAPE");
        uint256 start = gasleft();
        (result[0], result[1], result[2], result[3], result[4]) =
            @NAME@._evaluateFixedEqTermsBlobRaw(
                statement, 0, ood[0], ood[1], ood[2], ood[3], point
            );
        used = start - gasleft();
    }
}

'''

def generate():
    output = HEADER
    for field, baby in [("KoalaBear", False), ("BabyBear", True)]:
        reductions = (
            ["add(c0, shl(1, c5))", "add(c1, shl(1, c6))", "add(c2, shl(1, c7))", "add(c3, shl(1, c8))", "c4"]
            if baby else
            ["add(add(c0,c5),sub(bias,c8))", "add(c1,c6)", "add(add(add(c2,sub(bias,c5)),c7),c8)", "add(add(c3,sub(bias,c6)),c8)", "add(c4,sub(bias,c7))"]
        )
        for no_final in [False, True]:
            source = TEMPLATE
            base = "BabyBearBenchField" if baby else "KoalaBearExt5"
            replacements = {
                "@FIELD@": base,
                "@PACKED@": field + "PackedField",
                "@NAME@": field + "EqShifted" + ("NoFinal" if no_final else ""),
                "@MODULUS@": "0x78000001" if baby else "0x7f000001",
            }
            replacements.update({f"@R{i}@": r for i, r in enumerate(reductions)})
            for old, new in replacements.items():
                source = source.replace(old, new)
            if baby:
                source = source.replace("            let bias := shl(40, M)\n", "")
            if no_final:
                cut = source.index("for (uint256 i = 21;")
                prefix, body = source[:cut], source[cut:]
                for variable, limit in [("initialCurrent", 1), ("round0Current", 5), ("round1Current", 9), ("round2Current", 13)]:
                    line = f"{variable} = {base}.square({variable});"
                    body = body.replace(line, f"if (i > {limit}) {line}")
                source = prefix + body
            output += source
    target = ROOT / "test/helpers/BabyBearEqFollowup.sol"
    target.write_text(output)
    print(target)

if __name__ == "__main__":
    generate()
