#!/usr/bin/env python3
"""Generate matched square/equality preparation benchmarks from the native core."""
from generate_select_variants import ROOT,CORE,function,packed,reductions
import re
from generate_packed_fields import kernel

def generate():
    core=CORE.read_text()
    s='''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/generate_eq_variants.py.
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import { BabyBearBenchField } from "./BabyBearSelectVariants.sol";
import { BabyBearPackedField, KoalaBearPackedField } from "./BabyBearPackedFields.sol";
'''
    variants=[(field+'Eq'+suffix,baby,peel,fused) for field,baby in [('KoalaBear',False),('BabyBear',True)] for suffix,peel,fused in [('Baseline',False,False),('Peel',True,False),('Fused',False,True),('Combined',True,True),('PackedMul',True,True),('PackedSquare',True,True),('PackedEq',True,True),('NoFinalSquares',True,True),('PackedMulNoFinal',True,True)]]
    for name,baby,peel,fused in variants:
        field='BabyBearBenchField' if baby else 'KoalaBearExt5'
        eq=function(core,'_eqTerm')
        if baby:
            prefix=eq[:eq.index('            let bias :=')]
            tail=eq[eq.index('            let b := shl(2, M)'):]
            mid=''
            for i,v in enumerate(reductions('baby')):mid+=f'            let m{i} := '+(v if fused else f'mod({v}, M)')+'\n'
            eq=(prefix+mid+tail).replace('0x7f000001','0x78000001')
        elif fused:
            eq=re.sub(r'let m([0-4]) := mod\((.*), M\)',r'let m\1 := \2',eq)
        prep=function(core,'_evaluateFixedEqTermsBlobRaw').replace('KoalaBearExt5',field)
        if peel:
            initial='''            {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    q := mload(add(pointBase,672))
                    statementPointValue := and(calldataload(add(add(blob.offset,statementPointOffset),420)),not(sub(shl(96,1),1)))
                }
                statementEq = FIELD.mul(FIELD.ONE,_eqTerm(statementPointValue,q));
                initialEq = _eqTerm(initialCurrent,q);
                round0Eq = _eqTerm(round0Current,q);
                round1Eq = _eqTerm(round1Current,q);
                round2Eq = _eqTerm(round2Current,q);
                initialCurrent = FIELD.square(initialCurrent);
                round0Current = FIELD.square(round0Current);
                round1Current = FIELD.square(round1Current);
                round2Current = FIELD.square(round2Current);
            }
            for (uint256 i = 21; i > 0; --i) {'''.replace('FIELD',field)
            # All five first products have identity as their accumulator.
            initial=initial.replace(f'{field}.mul({field}.ONE,_eqTerm(statementPointValue,q))','_eqTerm(statementPointValue,q)')
            prep=prep.replace('            for (uint256 i = 22; i > 0; --i) {',initial)
        packedfield=('BabyBear' if baby else 'KoalaBear')+'PackedField'
        squarefield=field
        if name.endswith(('PackedMul','PackedSquare','PackedEq','NoFinalSquares','PackedMulNoFinal')):
            prep=prep.replace(field+'.mul(',packedfield+'.mul(')
        if name.endswith(('PackedSquare','PackedEq','NoFinalSquares')):
            prep=prep.replace(field+'.square(',packedfield+'.square(')
            squarefield=packedfield
        if name.endswith(('PackedEq','NoFinalSquares')):
            eq='    function _eqTerm(uint256 a,uint256 b) internal pure returns(uint256) {return '+packedfield+'.eq(a,b);}'
        if name.endswith(('NoFinalSquares','PackedMulNoFinal')):
            for variable,limit in [('initialCurrent',1),('round0Current',5),('round1Current',9),('round2Current',13)]:
                line=variable+' = '+squarefield+'.square('+variable+');'
                # First peeled iteration always has a subsequent consumer.
                cut=prep.index('for (uint256 i = 21;')
                prep=prep[:cut]+prep[cut:].replace(line,'if (i > '+str(limit)+') '+line)
        mulfield=packedfield if name.endswith(('PackedMul','PackedSquare','PackedEq','NoFinalSquares','PackedMulNoFinal')) else field
        s+=f'library {name} {{\n'+eq+'\n'+prep+'\n}\n'
        s+=f'''contract {name}Harness {{
    function mul(uint256 a,uint256 b) external pure returns(uint256) {{return {mulfield}.mul(a,b);}}
    function square(uint256 a) external pure returns (uint256) {{ return {squarefield}.square(a); }}
    function eq(uint256 a,uint256 b) external pure returns (uint256) {{ return {name}._eqTerm(a,b); }}
    function squares(uint256 a,uint256 n) external view returns (uint256 used,uint256 result) {{
        uint256 start=gasleft();result=a;
        for (uint256 i;i<n;++i) result={squarefield}.square(result);
        used=start-gasleft();
    }}
    function prepare(bytes calldata statement,uint256[4] memory ood,uint256[] memory point)
        external view returns (uint256 used,uint256[5] memory result) {{
        require(statement.length==440 && point.length==22,"SHAPE");
        uint256 start=gasleft();
        (result[0],result[1],result[2],result[3],result[4])={name}._evaluateFixedEqTermsBlobRaw(statement,0,ood[0],ood[1],ood[2],ood[3],point);
        used=start-gasleft();
    }}
}}
'''
    (ROOT/'test/helpers/BabyBearEqVariants.sol').write_text(s)

if __name__=='__main__':generate()
