#!/usr/bin/env python3
"""Four-product multiplication controls for the fixed equality workload."""
from generate_select_variants import ROOT, CORE, function, packed, reductions


def kernel(baby):
    fn = function(CORE.read_text(), '_mulBySelectTermExt5')
    fn = fn[:fn.index('            // acc *')]
    fn = fn.replace('uint256 acc, uint256 pointValue, uint256 scalar', 'uint256 acc, uint256 pointValue')
    fn = fn.replace('_mulBySelectTermExt5', 'mul')
    if baby:
        fn = fn.replace('0x7f000001', '0x78000001')
        r = reductions('baby')
    else:
        fn += '            let bias := shl(40, M)\n'
        r = ['add(add(c0,c5),sub(bias,c8))', 'add(c1,c6)', 'add(add(add(c2,sub(bias,c5)),c7),c8)', 'add(add(c3,sub(bias,c6)),c8)', 'add(c4,sub(bias,c7))']
    return fn, r


def generate():
    s = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/generate_packed_fields.py.
// Every retained convolution lane has at most four products below 2^64.
// The fifth middle product is added after extraction. Subtraction biases and
// equality intermediates fit below 2^73; final MOD precedes canonical packing.
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import { BabyBearBenchField } from "./BabyBearSelectVariants.sol";
'''
    tail = function(CORE.read_text(), '_eqTerm')
    tail = tail[tail.index('            let b := shl(2, M)'):]
    for baby in [False, True]:
        field = 'BabyBear' if baby else 'KoalaBear'
        base = 'BabyBearBenchField' if baby else 'KoalaBearExt5'
        prefix, r = kernel(baby)
        mul = prefix + '            out := ' + packed([f'mod({v},M)' for v in r]) + '\n        }\n    }'
        eq = prefix.replace('function mul(', 'function eq(').replace('uint256 acc, uint256 pointValue', 'uint256 a, uint256 pointValue')
        # The original equality tail uses ai/bi; decode only at its consumption.
        eq = eq.replace('acc)', 'a)')
        for i in range(5):
            eq += f'            let m{i} := {r[i]}\n'
            eq += f'            let a{i} := and(shr({224-32*i},a),0xffffffff)\n'
            eq += f'            let b{i} := and(shr({224-32*i},pointValue),0xffffffff)\n'
        eqtail = tail
        for i in range(5):
            eqtail = eqtail.replace(f"p{i}",f"a{i}").replace(f"q{i}",f"b{i}")
        eq += eqtail
        s += f'''library {field}PackedField {{
    uint256 internal constant ONE = uint256(1)<<224;
    function add(uint256 a,uint256 b) internal pure returns(uint256) {{return {base}.add(a,b);}}
    function sub(uint256 a,uint256 b) internal pure returns(uint256) {{return {base}.sub(a,b);}}
    function square(uint256 a) internal pure returns(uint256) {{return mul(a,a);}}
'''+mul+'\n'+eq+'\n}\n'
    (ROOT/'test/helpers/BabyBearPackedFields.sol').write_text(s)


if __name__ == '__main__':
    generate()
