#!/usr/bin/env python3
"""Experiment: keep both Kronecker forms of the accumulator across select steps."""
from generate_select_variants import ROOT,CORE,function,packed,reductions
import re

def generate():
    core=CORE.read_text()
    s='''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/generate_select_forms.py.
// Each accumulator is two words with four canonical coefficients in 64-bit lanes.
// The four-term convolution lanes stay below 2^64. Final coefficient reductions
// precede every repack, including when scalar is in [0,2*M-2].
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import { BabyBearBenchField, BabyBearSelectPrepackedCombined } from "./BabyBearSelectVariants.sol";
import { BabyBearPackedField, KoalaBearPackedField } from "./BabyBearPackedFields.sol";
'''
    for baby in [False,True]:
        name=('BabyBear' if baby else 'KoalaBear')+'SelectForms'
        field='BabyBearBenchField' if baby else 'KoalaBearExt5'
        prime='0x78000001' if baby else '0x7f000001'
        r=reductions('baby') if baby else ['add(add(c0,c5),sub(bias,c8))','add(c1,c6)','add(add(add(c2,sub(bias,c5)),c7),c8)','add(add(c3,sub(bias,c6)),c8)','add(c4,sub(bias,c7))']
        low='or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))'
        rev='or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))'
        lib=f'''library {name} {{
    function _multiply(uint256 aLow,uint256 aRev,uint256 ptr,uint256 scalar)
        private pure returns (uint256 lowOut,uint256 revOut) {{
        assembly ("memory-safe") {{
            let M := {prime}
            let bLow := mload(ptr)
            let c4 := add(shr(192,mul(aLow,mload(add(ptr,32)))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let low := mul(aLow,bLow)
            let high := mul(aRev,mload(add(ptr,64)))
            let c0 := and(low,0xffffffffffffffff)
            let c1 := and(shr(64,low),0xffffffffffffffff)
            let c2 := and(shr(128,low),0xffffffffffffffff)
            let c3 := shr(192,low)
            let c5 := shr(192,high)
            let c6 := and(shr(128,high),0xffffffffffffffff)
            let c7 := and(shr(64,high),0xffffffffffffffff)
            let c8 := and(high,0xffffffffffffffff)
'''
        if not baby:lib+='            let bias := shl(40,M)\n'
        a=['and(aLow,0xffffffff)','and(shr(64,aLow),0xffffffff)','and(shr(128,aLow),0xffffffff)','shr(192,aLow)','and(aRev,0xffffffff)']
        for i,v in enumerate(r):lib+=f'            let o{i} := mod(add({a[i]},mul(scalar,{v})),M)\n'
        lib+=f'''            lowOut := {low}
            revOut := {rev}
        }}
    }}
    function _initial(uint256 ptr,uint256 scalar) private pure returns (uint256 lowOut,uint256 revOut) {{
        assembly ("memory-safe") {{
            let M := {prime}
            let b := mload(ptr)
            let o0 := mod(add(1,mul(and(b,0xffffffff),scalar)),M)
            let o1 := mulmod(and(shr(64,b),0xffffffff),scalar,M)
            let o2 := mulmod(and(shr(128,b),0xffffffff),scalar,M)
            let o3 := mulmod(shr(192,b),scalar,M)
            let o4 := mulmod(shr(192,mload(add(ptr,32))),scalar,M)
            lowOut := {low}
            revOut := {rev}
        }}
    }}
    function _pack(uint256 low,uint256 rev) private pure returns (uint256 out) {{
        assembly ("memory-safe") {{
            out := {packed(['and(low,0xffffffff)','and(shr(64,low),0xffffffff)','and(shr(128,low),0xffffffff)','shr(192,low)','and(rev,0xffffffff)'])}
        }}
    }}
    function _selectPolyEvalFixed(uint256 current,uint256[] memory cache,uint256 offset,uint256 n)
        internal pure returns(uint256) {{
        if(n==0) return uint256(1)<<224;
        uint256 ptr;
        assembly ("memory-safe") {{ptr:=add(add(cache,32),mul(sub(add(offset,n),5),96))}}
        uint256 low;uint256 rev;
        unchecked {{
            (low,rev)=_initial(ptr,current+({prime}-1));
            for(uint256 i=n-1;i>0;--i) {{
                assembly ("memory-safe") {{current:=mulmod(current,current,{prime}) ptr:=sub(ptr,96)}}
                (low,rev)=_multiply(low,rev,ptr,current+({prime}-1));
            }}
        }}
        return _pack(low,rev);
    }}
    function _selectPolyEvalFixedPair(uint256 current0,uint256 current1,uint256[] memory cache,uint256 offset,uint256 n)
        internal pure returns(uint256 x,uint256 y) {{
        if(n==0) return (uint256(1)<<224,uint256(1)<<224);
        uint256 ptr;
        assembly ("memory-safe") {{ptr:=add(add(cache,32),mul(sub(add(offset,n),5),96))}}
        uint256 low0;uint256 rev0;uint256 low1;uint256 rev1;
        unchecked {{
            (low0,rev0)=_initial(ptr,current0+({prime}-1));
            (low1,rev1)=_initial(ptr,current1+({prime}-1));
            for(uint256 i=n-1;i>0;--i) {{
                assembly ("memory-safe") {{current0:=mulmod(current0,current0,{prime}) current1:=mulmod(current1,current1,{prime}) ptr:=sub(ptr,96)}}
                (low0,rev0)=_multiply(low0,rev0,ptr,current0+({prime}-1));
                (low1,rev1)=_multiply(low1,rev1,ptr,current1+({prime}-1));
            }}
        }}
        return (_pack(low0,rev0),_pack(low1,rev1));
    }}
'''
        for fn in [f'_evaluateConstraintSelectRaw{n}WithPrecomputedEq' for n in [18,14,10]]+['_hornerStep']:
            lib+=function(core,fn).replace('KoalaBearExt5',field)+'\n'
        s+=lib+'}\n'
        s+=f'''contract {name}Harness {{
    function chains(uint256[] memory point,uint256 a,uint256 b,uint256 offset,uint256 n)
        external view returns(uint256 used,uint256 x,uint256 y) {{
        require(point.length==22 && offset>=4 && offset<=22 && n<=22-offset,"SHAPE");
        uint256 start=gasleft();
        uint256[] memory cache=BabyBearSelectPrepackedCombined.prepare(point);
        (x,y)={name}._selectPolyEvalFixedPair(a,b,cache,offset,n);
        used=start-gasleft();
    }}
    function single(uint256[] memory point,uint256 a,uint256 offset,uint256 n) external pure returns(uint256) {{
        require(point.length==22 && offset>=4 && offset<=22 && n<=22-offset,"SHAPE");
        return {name}._selectPolyEvalFixed(a,BabyBearSelectPrepackedCombined.prepare(point),offset,n);
    }}
    function batch(uint256[] memory point,uint256[][3] memory selectors,uint256[3] memory challenges,uint256[3] memory eqs)
        external view returns(uint256 used,uint256[3] memory result) {{
        require(point.length==22 && selectors[0].length==38 && selectors[1].length==31 && selectors[2].length==19,"SHAPE");
        uint256 start=gasleft();
        uint256[] memory cache=BabyBearSelectPrepackedCombined.prepare(point);
        result[0]={name}._evaluateConstraintSelectRaw18WithPrecomputedEq(challenges[0],eqs[0],selectors[0],cache);
        result[1]={name}._evaluateConstraintSelectRaw14WithPrecomputedEq(challenges[1],eqs[1],selectors[1],cache);
        result[2]={name}._evaluateConstraintSelectRaw10WithPrecomputedEq(challenges[2],eqs[2],selectors[2],cache);
        used=start-gasleft();
    }}
}}
'''
    # Match the select recurrence and change only the Horner field multiplication.
    original=s
    for field,base,packedfield in [('KoalaBear','KoalaBearExt5','KoalaBearPackedField'),('BabyBear','BabyBearBenchField','BabyBearPackedField')]:
        oldname=field+'SelectForms'
        start=original.index('library '+oldname+' {')
        cstart=original.index('contract '+oldname+'Harness {',start)
        end=len(original)
        for marker in ['library KoalaBearSelectForms {','library BabyBearSelectForms {']:
            pos=original.find(marker,cstart+1)
            if pos!=-1:end=min(end,pos)
        block=original[start:end]
        clone=block.replace(oldname,oldname+'PackedHorner').replace(base+'.add(',packedfield+'.add(').replace(base+'.mul(',packedfield+'.mul(')
        s+=clone
        shared=block.replace(oldname,oldname+'SharedPair')
        before=function(shared,'_multiply')
        after=before.replace('uint256 ptr,uint256 scalar','uint256 bLow,uint256 bMid,uint256 bRev,uint256 scalar')
        after=after.replace('            let bLow := mload(ptr)\n','').replace('mload(add(ptr,32))','bMid').replace('mload(add(ptr,64))','bRev')
        shared=shared.replace(before,after)
        for fn in ['_selectPolyEvalFixed','_selectPolyEvalFixedPair']:
            before=function(shared,fn)
            after=re.sub(r'_multiply\((low[01]?,rev[01]?),ptr,',r'_multiply(\1,bLow,bMid,bRev,',before)
            marker='                (low' if fn.endswith('Fixed') else '                (low0'
            where=after.index(marker)
            after=after[:where]+'                uint256 bLow;uint256 bMid;uint256 bRev;\n                assembly ("memory-safe") {bLow:=mload(ptr) bMid:=mload(add(ptr,32)) bRev:=mload(add(ptr,64))}\n'+after[where:]
            shared=shared.replace(before,after)
        s+=shared
    (ROOT/'test/helpers/BabyBearSelectForms.sol').write_text(s)

if __name__=='__main__':generate()
