#!/usr/bin/env python3
"""Generate matched row-evaluation experiments. Run the select generator first."""
from pathlib import Path
import re
from generate_select_variants import ROOT,function,body_with_reduction,packed,reductions

UTIL=ROOT/'src/whir/k22_jb100_ext5_lir4_ff4_rsv3_pow28/WhirVerifierUtils5.sol'

def adds(terms):
    result=terms[0]
    for term in terms[1:]:result=f'add({result}, {term})'
    return result

def generate():
    utils=UTIL.read_text()
    header='''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/generate_row_variants.py.
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import { BabyBearBenchField } from "./BabyBearSelectVariants.sol";
import { KoalaBearPackedField, BabyBearPackedField } from "./BabyBearPackedFields.sol";
'''
    libs=[];contracts=[]
    for baby in [False,True]:
        field='BabyBear' if baby else 'KoalaBear'
        arithmetic='BabyBearBenchField' if baby else 'KoalaBearExt5'
        prime='0x78000001' if baby else '0x7f000001'
        for variant in ['Nine','Five','Kronecker','KroneckerFive','KroneckerStream']:
            name=f'{field}Row{variant}'
            helpers='\n'.join(function(utils,x) for x in ['_computeDim4EqWeights','_storeDim4EqWeightPair'])
            fused=function(utils,'_hashAndEvaluateExtension5RowDim4BlobUnpacked')
            dot=function(utils,'_dotExt5Weights16Unpacked').replace('private pure','internal pure')
            if baby:
                helpers=helpers.replace('KoalaBearExt5',arithmetic)
                fused=fused.replace('00ffffff','07ffffff')
                dot=body_with_reduction(dot,'baby').replace('0x7f000001',prime)
            # Each preprocessor consumes 16 canonical packed weights and returns raw words.
            words={'Nine':5,'Five':9,'Kronecker':3,'KroneckerFive':3,'KroneckerStream':3}[variant]
            prepare=f'''    function prepare(uint256 packedPtr) internal pure returns (uint256 ptr) {{
        assembly ("memory-safe") {{
            ptr := mload(0x40)
            mstore(0x40, add(ptr, {16*words*32}))
            for {{ let i := 0 }} lt(i, 16) {{ i := add(i, 1) }} {{
                let a := mload(add(packedPtr, shl(5, i)))
                let dst := add(ptr, mul(i, {words*32}))
                let b0 := shr(224, a)
                let b1 := and(shr(192, a), 0xffffffff)
                let b2 := and(shr(160, a), 0xffffffff)
                let b3 := and(shr(128, a), 0xffffffff)
                let b4 := and(shr(96, a), 0xffffffff)
'''
            if variant.startswith('Kronecker'):
                prepare+='''                let low := or(or(b0, shl(64, b1)), or(shl(128, b2), shl(192, b3)))
                mstore(dst, low)
                mstore(add(dst,32), or(shr(64,low),shl(192,b4)))
                mstore(add(dst,64), or(or(b4,shl(64,b3)),or(shl(128,b2),shl(192,b1))))
'''
            else:
                for j in range(5):prepare+=f'                mstore(add(dst,{32*j}),b{j})\n'
                if variant=='Five':
                    transforms=['shl(1,b1)','shl(1,b2)','shl(1,b3)','shl(1,b4)'] if baby else [f'mod(sub(add(b1,{prime}),b4),{prime})',f'mod(sub(add(b0,{prime}),b3),{prime})',f'mod(sub(add(b4,{prime}),b2),{prime})',f'mod(sub(add(add(b3,b4),{prime}),b1),{prime})']
                    for j,v in enumerate(transforms,5):prepare+=f'                mstore(add(dst,{32*j}),{v})\n'
            prepare+='            }\n        }\n    }\n'
            if variant!='Nine':
                # Keep the original unrolled 16-row caller and replace only accumulation.
                count=5 if variant in ['Five','KroneckerFive','KroneckerStream'] else 9
                signature=dot[:dot.index('        assembly')]
                new=signature+f'        assembly ("memory-safe") {{\n            let M := {prime}\n'
                for j in range(count):new+=f'            let c{j} := 0\n'
                new+='            function accumulate(a,w,'+','.join(f'd{i}' for i in range(count))+') -> '+','.join(f'e{i}' for i in range(count))+' {\n'
                for j in range(5):new+=f'                let a{j} := '+('shr(224,a)' if j==0 else f'and(shr({224-32*j},a),0xffffffff)')+'\n'
                if variant=='Five':
                    matrix=[[0,8,7,6,5],[1,0,8,7,6],[2,1,0,8,7],[3,2,1,0,8],[4,3,2,1,0]] if baby else [[0,4,3,2,5],[1,0,4,3,2],[2,5,6,7,8],[3,2,5,6,7],[4,3,2,5,6]]
                    for j,row in enumerate(matrix):
                        terms=[f'mul(a{k},mload(add(w,{32*b})))' for k,b in enumerate(row)]
                        new+=f'                e{j} := add(d{j},{adds(terms)})\n'
                else:
                    new+='''                let lowA := or(or(a0,shl(64,a1)),or(shl(128,a2),shl(192,a3)))
                let lowB := mload(w)
                let low := mul(lowA,lowB)
                let high := mul(or(or(a4,shl(64,a3)),or(shl(128,a2),shl(192,a1))),mload(add(w,64)))
                let mid := add(shr(192,mul(lowA,mload(add(w,32)))),mul(a4,and(lowB,0xffffffff)))
'''
                    expr=['and(low,0xffffffffffffffff)','and(shr(64,low),0xffffffffffffffff)','and(shr(128,low),0xffffffffffffffff)','shr(192,low)','mid','shr(192,high)','and(shr(128,high),0xffffffffffffffff)','and(shr(64,high),0xffffffffffffffff)','and(high,0xffffffffffffffff)']
                    if variant in ['KroneckerFive','KroneckerStream']:
                        for j,v in enumerate(expr):new+=f'                let x{j} := {v}\n'
                        if baby:out=[v.replace('c','x') for v in reductions('baby')]
                        else:
                            new+=f'                let bias := shl(40,{prime})\n'
                            out=['add(add(x0,x5),sub(bias,x8))','add(x1,x6)','add(add(add(x2,sub(bias,x5)),x7),x8)','add(add(x3,sub(bias,x6)),x8)','add(x4,sub(bias,x7))']
                        for j,v in enumerate(out):new+=f'                e{j} := add(d{j},{v})\n'
                    else:
                        for j,v in enumerate(expr):new+=f'                e{j} := add(d{j},{v})\n'
                new+='            }\n'
                cs=','.join(f'c{i}' for i in range(count))
                for i in range(16):new+=f'            {cs} := accumulate(v{i},add(weightsPtr,{i*32*words}),{cs})\n'
                if count==5:new+='            out := '+packed([f'mod(c{i},M)' for i in range(5)])+'\n        }\n    }'
                else:
                    end=dot.index('            out :=') if baby else dot.index('            let bias :=')
                    new+=dot[end:]
                dot=new
            if variant=='KroneckerStream':
                signature=fused[:fused.index('        uint256 src;')]
                start=fused.index('            function validateExt5(packed)')
                end=fused.index('            validateExt5(v0)',start)
                validate=fused[start:end]
                start=dot.index('            let M :=')
                end=dot.index('            c0,c1,c2,c3,c4 := accumulate(v0')
                accum=dot[start:end]
                fused=signature+'        assembly ("memory-safe") {\n            let src := add(blob.offset,offset)\n            let lowMask := not(sub(shl(96,1),1))\n'+validate+accum
                for i in range(16):
                    fused+=f'            {{ let v := and(calldataload(add(src,{i*20})),lowMask) validateExt5(v) c0,c1,c2,c3,c4 := accumulate(v,add(weightsPtr,{i*96}),c0,c1,c2,c3,c4) }}\n'
                fused+='            evalValue := '+packed([f'mod(c{i},M)' for i in range(5)])+'\n'
                fused+='            let ptr := mload(0x40)\n            mstore8(ptr,0)\n            calldatacopy(add(ptr,1),src,320)\n            digest := and(keccak256(ptr,321),lowMask)\n        }\n    }'
            # Stage loads for the isolated arithmetic measurement. The fused helper
            # above retains the original production caller and its 16 live row values.
            arraydot='    function dotArray(uint256 weightsPtr, uint256[16] memory values) internal pure returns (uint256 out) {\n'+dot[dot.index('        assembly'):]
            arraydot=re.sub(r'\bv(\d+)\b',lambda m:f'mload(add(values,{32*int(m[1])}))',arraydot)
            libs.append(f'library {name} {{\n'+helpers+'\n'+prepare+'\n'+fused+'\n'+dot+'\n'+arraydot+'\n}\n')
            vs=','.join(f'values[{i}]' for i in range(16))
            contracts.append(f'''contract {name}Harness {{
    function dot(uint256[16] memory values,uint256[16] memory weights) external view returns (uint256 used,uint256 result) {{
        uint256 packedPtr;
        assembly ("memory-safe") {{ packedPtr := weights }}
        uint256 ptr={name}.prepare(packedPtr);
        uint256 start=gasleft();
        result={name}.dotArray(ptr,values);
        used=start-gasleft();
    }}
    function batch(bytes calldata blob,uint256[4] memory point,uint256 count)
        external view returns (uint256 setupGas,uint256 rowGas,uint256 result,bytes32 digest) {{
        require(blob.length==count*320 && count>0,"SHAPE");
        uint256 start=gasleft();
        uint256 packedPtr={name}._computeDim4EqWeights(point[0],point[1],point[2],point[3]);
        uint256 ptr={name}.prepare(packedPtr);
        setupGas=start-gasleft();
        start=gasleft();
        for(uint256 i;i<count;++i) {{
            (bytes32 h,uint256 value)={name}._hashAndEvaluateExtension5RowDim4BlobUnpacked(blob,i*320,ptr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
            result^=value;digest^=h;
        }}
        rowGas=start-gasleft();
    }}
}}
''')
            if variant=='KroneckerStream':
                original_lib=libs[-1];original_contract=contracts[-1]
                libs.append(original_lib.replace(name,name+'PackedWeights').replace(arithmetic+'.mul(',field+'PackedField.mul('))
                contracts.append(original_contract.replace(name,name+'PackedWeights'))
                loop=original_lib.replace(name,name+'Loop')
                start=loop.index('            { let v := and(calldataload(add(src,0))')
                end=loop.index('            evalValue :=',start)
                loop=loop[:start]+'            for { let i := 0 } lt(i,16) { i := add(i,1) } { let v := and(calldataload(add(src,mul(i,20))),lowMask) validateExt5(v) c0,c1,c2,c3,c4 := accumulate(v,add(weightsPtr,mul(i,96)),c0,c1,c2,c3,c4) }\n'+loop[end:]
                libs.append(loop);contracts.append(original_contract.replace(name,name+'Loop'))
    (ROOT/'test/helpers/BabyBearRowVariants.sol').write_text(header+'\n'.join(libs+contracts))

if __name__=='__main__':generate()
