#!/usr/bin/env python3
"""Generate isolated select experiments from the recorded native core.

Run from the repository root. This does not edit production Solidity.
The generated baseline preserves the production single/pair and Horner callers.
"""
from pathlib import Path
import hashlib
import re

ROOT = Path(__file__).resolve().parents[2]
CORE = ROOT / 'src/whir/k22_jb100_ext5_lir4_ff4_rsv3_pow28/WhirVerifierCore5.sol'
FIELD = ROOT / 'src/field/KoalaBearExt5.sol'

def function(text, name):
    start = text.index('    function ' + name + '(')
    brace = text.index('{', start)
    level, end = 1, brace + 1
    while level:
        if text[end] == '{': level += 1
        if text[end] == '}': level -= 1
        end += 1
    return text[start:end]

def packed(expressions):
    terms = [f'shl({224-32*i}, {v})' for i,v in enumerate(expressions)]
    return f'or(or(or({terms[0]}, {terms[1]}), or({terms[2]}, {terms[3]})), {terms[4]})'

def reductions(poly):
    if poly == 'baby': return ['add(c0, shl(1, c5))','add(c1, shl(1, c6))','add(c2, shl(1, c7))','add(c3, shl(1, c8))','c4']
    if poly == 'reciprocal': return ['add(add(c0, c5), c7)','add(add(c1, c6), c8)','add(c2, c7)','add(add(add(c3, c5), c7), c8)','add(add(c4, c6), c8)']
    raise ValueError(poly)

def body_with_reduction(text, poly, select=False):
    prefix = text[:text.index('            // acc *' if select else '            let bias :=')]
    expr = reductions(poly)
    if select:
        expr = [f'add({"shr(224, acc)" if i==0 else f"and(shr({224-32*i}, acc), mask)"}, mul(scalar, {v}))' for i,v in enumerate(expr)]
    return prefix + '            out := ' + packed([f'mod({v}, M)' for v in expr]) + '\n        }\n    }'

def generate():
    core, field = CORE.read_text(), FIELD.read_text()
    names = ['_selectPolyEvalFixed', '_selectPolyEvalFixedPair', '_mulBySelectTermExt5']
    common_names = [f'_evaluateConstraintSelectRaw{n}WithPrecomputedEq' for n in [18,14,10]] + ['_hornerStep']
    header = '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.28;\n\n'
    header += '// Generated by script/babybear/generate_select_variants.py.\n'
    header += '// Native core SHA-256: ' + hashlib.sha256(core.encode()).hexdigest() + '\n'
    header += 'import { KoalaBear } from "../../src/field/KoalaBear.sol";\nimport { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";\n'
    bb = 'library BabyBearBenchField {\n    uint256 internal constant MODULUS = 0x78000001;\n    uint256 internal constant ONE = uint256(1) << 224;\n'
    for name in ['add','sub','_mulPacked','_squarePacked']:
        fn = function(field,name)
        if name not in ['add','sub']: fn=body_with_reduction(fn,'baby').replace('private','internal').replace('_mulPacked','mul').replace('_squarePacked','square')
        fn=fn.replace('7f000001','78000001').replace('00ffffff','07ffffff')
        bb+=fn+'\n'
    bb+='}\n'
    contracts=[]; libs=[]
    variants=[('Baseline',False,False,False),('Peel',True,False,False),('Branchless',False,True,False),('Raw',False,False,True),('Combined',True,True,True),('Prepacked',False,False,True),('PrepackedCombined',True,True,True)]
    for is_bb in [False,True]:
        fieldname='BabyBear' if is_bb else 'KoalaBear'
        fieldref='BabyBearBenchField' if is_bb else 'KoalaBearExt5'
        prime='0x78000001' if is_bb else '0x7f000001'
        for suffix,peel,branchless,raw in variants:
            prepacked=suffix.startswith('Prepacked')
            lib=fieldname+'Select'+suffix
            fns=[]
            for name in names+common_names:
                fn=function(core,name)
                if is_bb:
                    if name=='_mulBySelectTermExt5':fn=body_with_reduction(fn,'baby',True)
                    fn=fn.replace('KoalaBearExt5','BabyBearBenchField').replace('KoalaBear.MODULUS','BabyBearBenchField.MODULUS').replace('0x7f000001','0x78000001')
                    fn=re.sub(r'KoalaBear.mul\((current[01]?), \1\)',r'mulmod(\1, \1, BabyBearBenchField.MODULUS)',fn)
                if name in names[:2]:
                    if peel:
                        init='''            uint256 i = numVariables;
            if (i != 0) {
                --i;
'''
                        if name==names[0]:
                            init+=f'''                uint256 scalar = current == 0 ? {prime} - 1 : current - 1;
                acc = _initialSelect(fullPoint[pointOffset + i], scalar);
                current = mulmod(current, current, {prime});
'''
                        else:
                            init+=f'''                uint256 pointValue = fullPoint[pointOffset + i];
                uint256 scalar0 = current0 == 0 ? {prime} - 1 : current0 - 1;
                uint256 scalar1 = current1 == 0 ? {prime} - 1 : current1 - 1;
                acc0 = _initialSelect(pointValue, scalar0);
                acc1 = _initialSelect(pointValue, scalar1);
                current0 = mulmod(current0, current0, {prime});
                current1 = mulmod(current1, current1, {prime});
'''
                        init+='            }\n            for (; i > 0; --i) {'
                        fn=fn.replace('            for (uint256 i = numVariables; i > 0; --i) {',init)
                    if branchless:
                        fn=re.sub(r'(current[01]?) == 0 \? (?:KoalaBear.MODULUS|BabyBearBenchField.MODULUS|0x7f000001|0x78000001) - 1 : \1 - 1',lambda m:f'{m[1]} + ({prime} - 1)',fn)
                    if raw:
                        fn=re.sub(r'fullPoint\[pointOffset \+ i( - 1)?\]',lambda m:'_loadPoint(fullPoint, pointOffset + i'+(m[1] or '')+')',fn)
                    if prepacked:
                        fn=fn.replace('_loadPoint(', '_cachedAddress(').replace('_mulBySelectTermExt5(', '_mulBySelectTermCached(').replace('_initialSelect(', '_initialCached(')
                fns.append(fn)
            init=packed(['mod(add(1, mul(shr(224, point), scalar)), M)']+[f'mulmod(and(shr({224-32*i}, point), 0xffffffff), scalar, M)' for i in range(1,5)])
            helpers=f'''    // Inputs are canonical; scalar may be <= 2*M-2. Outputs are canonical.
    function _initialSelect(uint256 point, uint256 scalar) private pure returns (uint256 out) {{
        assembly ("memory-safe") {{ let M := {prime} out := {init} }}
    }}
    // Fixed production windows are validated by the external harness before this call.
    function _loadPoint(uint256[] memory point, uint256 i) private pure returns (uint256 v) {{
        assembly ("memory-safe") {{ v := mload(add(add(point, 32), shl(5, i))) }}
    }}
'''
            if prepacked:
                kernel=fns[2].replace('_mulBySelectTermExt5(', '_mulBySelectTermCached(')
                start=kernel.index('                let b0 :=')
                end=kernel.index('            let laneMask :=')
                kernel=kernel[:start]+'''                let bLow := mload(pointValue)
                let aLow := or(or(a0, shl(64, a1)), or(shl(128, a2), shl(192, a3)))
                c4 := add(shr(192, mul(aLow, mload(add(pointValue, 32)))), mul(a4, and(bLow, 0xffffffff)))
                low := mul(aLow, bLow)
                high := mul(or(or(a4, shl(64, a3)), or(shl(128, a2), shl(192, a1))), mload(add(pointValue, 64)))
            }
'''+kernel[end:]
                helpers+=kernel+'\n'+'''    function _cachedAddress(uint256[] memory cache, uint256 index) private pure returns (uint256 ptr) {
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(index, 4), 96)) }
    }
    // All three native windows are suffixes of point[4..22). Cache each point once.
    function prepare(uint256[] memory point) internal pure returns (uint256[] memory cache) {
        assembly ("memory-safe") {
            cache := mload(0x40)
            mstore(cache, 54)
            mstore(0x40, add(cache, 1760))
            let dst := add(cache, 32)
            for { let src := add(point, 160) } lt(src, add(point, 736)) { src := add(src, 32) dst := add(dst, 96) } {
                let b := mload(src)
                let b0 := shr(224, b)
                let b1 := and(shr(192, b), 0xffffffff)
                let b2 := and(shr(160, b), 0xffffffff)
                let b3 := and(shr(128, b), 0xffffffff)
                let b4 := and(shr(96, b), 0xffffffff)
                let low := or(or(b0, shl(64, b1)), or(shl(128, b2), shl(192, b3)))
                mstore(dst, low)
                mstore(add(dst, 32), or(shr(64, low), shl(192, b4)))
                mstore(add(dst, 64), or(or(b4, shl(64, b3)), or(shl(128, b2), shl(192, b1))))
            }
        }
    }
'''
                init_c=packed(['mod(add(1, mul(and(low, 0xffffffff), scalar)), M)']+[f'mulmod({"shr(192, mload(add(ptr, 32)))" if i==4 else ("shr(192, low)" if i==3 else f"and(shr({64*i}, low), 0xffffffff)")}, scalar, M)' for i in range(1,5)])
                helpers+=f'''    function _initialCached(uint256 ptr, uint256 scalar) private pure returns (uint256 out) {{
        assembly ("memory-safe") {{ let M := {prime} let low := mload(ptr) out := {init_c} }}
    }}
'''
            libs.append('library '+lib+' {\n'+'\n\n'.join(fns)+'\n'+helpers+'}\n')
            prep=f'point={lib}.prepare(point);' if prepacked else ''
            extra_require='require(point.length == 22 && offset >= 4, "CACHE_POINT");' if prepacked else ''
            contracts.append(f'''contract {lib}Harness {{
    function term(uint256 a, uint256 b, uint256 scalar) external pure returns (uint256) {{
        return {lib}._mulBySelectTermExt5(a,b,scalar);
    }}
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external view returns (uint256 used, uint256 x, uint256 y) {{
        require(offset <= point.length && n <= point.length-offset, "POINT");
        {extra_require}
        uint256 start = gasleft();
        {prep}
        (x,y)={lib}._selectPolyEvalFixedPair(a,b,point,offset,n);
        used=start-gasleft();
    }}
    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external pure returns (uint256) {{
        require(offset <= point.length && n <= point.length-offset, "POINT");
        {extra_require}
        {prep}
        return {lib}._selectPolyEvalFixed(a,point,offset,n);
    }}
    function batch(uint256[] memory point, uint256[][3] memory selectors,
        uint256[3] memory challenges, uint256[3] memory eqs)
        external view returns (uint256 used, uint256[3] memory results) {{
        require(point.length==22 && selectors[0].length==38 && selectors[1].length==31 && selectors[2].length==19,"SHAPE");
        uint256 start=gasleft();
        {prep}
        results[0]={lib}._evaluateConstraintSelectRaw18WithPrecomputedEq(challenges[0],eqs[0],selectors[0],point);
        results[1]={lib}._evaluateConstraintSelectRaw14WithPrecomputedEq(challenges[1],eqs[1],selectors[1],point);
        results[2]={lib}._evaluateConstraintSelectRaw10WithPrecomputedEq(challenges[2],eqs[2],selectors[2],point);
        used=start-gasleft();
    }}
}}
''')
            if lib == 'KoalaBearSelectPrepackedCombined':
                name='KoalaBearSelectReciprocal'
                reciprocal=libs[-1].replace(lib,name)
                for kernel_name in ['_mulBySelectTermExt5','_mulBySelectTermCached']:
                    before=function(reciprocal,kernel_name)
                    reciprocal=reciprocal.replace(before,body_with_reduction(before,'reciprocal',True))
                for chain_name in names[:2]:
                    before=function(reciprocal,chain_name)
                    conversion='acc = _fromReciprocal(acc);' if chain_name==names[0] else 'acc0 = _fromReciprocal(acc0); acc1 = _fromReciprocal(acc1);'
                    reciprocal=reciprocal.replace(before,before[:-1]+conversion+'\n    }')
                reciprocal=reciprocal.replace('function prepare(', 'function _prepareConverted(')
                basis=[]
                for fn,expr in [('_toReciprocal',['sub(add(a0, M), a3)','sub(add(a4, M), a2)','sub(add(add(a3, a4), M), a1)','a2','sub(add(a1, M), a4)']),('_fromReciprocal',['add(add(a0, a2), a4)','add(add(a1, a3), a4)','a3','add(a2, a4)','add(a1, a3)'])]:
                    basis.append(f'''    function {fn}(uint256 a) internal pure returns (uint256 out) {{
        assembly ("memory-safe") {{
            let M := 0x7f000001
            let a0 := shr(224, a)
            let a1 := and(shr(192, a), 0xffffffff)
            let a2 := and(shr(160, a), 0xffffffff)
            let a3 := and(shr(128, a), 0xffffffff)
            let a4 := and(shr(96, a), 0xffffffff)
            out := {packed([f'mod({v}, M)' for v in expr])}
        }}
    }}
''')
                basis.append('''    function prepare(uint256[] memory point) internal pure returns (uint256[] memory) {
        uint256[] memory converted = new uint256[](22);
        for (uint256 i=4; i<22; ++i) converted[i] = _toReciprocal(point[i]);
        return _prepareConverted(converted);
    }
''')
                reciprocal=reciprocal.rstrip()[:-1]+'\n'+''.join(basis)+'}\n'
                libs.append(reciprocal)
                wrapper=contracts[-1].replace(lib,name)
                wrapper=wrapper.replace(f'return {name}._mulBySelectTermExt5(a,b,scalar);',f'return {name}._fromReciprocal({name}._mulBySelectTermExt5({name}._toReciprocal(a),{name}._toReciprocal(b),scalar));')
                contracts.append(wrapper)
    (ROOT/'test/helpers/BabyBearSelectVariants.sol').write_text(header+bb+'\n'.join(libs+contracts))

if __name__=='__main__':generate()
