// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/eq_followup_generate.py.
// Equality uses 2*(a-1/2)*(q-1/2)+1/2. Canonical coefficient forms persist
// across the accumulator chain. See testdata/babybear/followup-eq/bounds.md.
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import { BabyBearBenchField } from "./BabyBearSelectVariants.sol";
import { BabyBearPackedField, KoalaBearPackedField } from "./BabyBearPackedFields.sol";

library KoalaBearEqPersistentStatement {

    function _unpackForms(uint256 a) private pure returns(uint256 low,uint256 rev) {
        assembly("memory-safe") {
            let a0:=shr(224,a) let a1:=and(shr(192,a),0xffffffff) let a2:=and(shr(160,a),0xffffffff) let a3:=and(shr(128,a),0xffffffff) let a4:=and(shr(96,a),0xffffffff)
            low:=or(or(a0,shl(64,a1)),or(shl(128,a2),shl(192,a3)))
            rev:=or(or(a4,shl(64,a3)),or(shl(128,a2),shl(192,a1)))
        }
    }
    function _setPoint(uint256 ptr,uint256 a) private pure { (uint256 low,uint256 rev)=_unpackForms(a); assembly("memory-safe"){mstore(ptr,low) mstore(add(ptr,32),rev)} }
    function _pointEq(uint256 ptr,uint256 pointPtr,uint256[4] memory cache,bool initial) private pure {
        assembly("memory-safe") {
            let al:=mload(pointPtr) let ar:=mload(add(pointPtr,32)) let low let rev
            { let aLow:=al let aRev:=ar let outLow let outRev
            
            let M := 0x7f000001
            let mask := 0xffffffff

            let convolutionLow
            let high
            let c4
            {
                let a0 := mod(add(and(aLow,0xffffffff),shr(1,M)),M)
                aLow := or(and(aLow,not(0xffffffff)),a0)
                let a4 := and(aRev,0xffffffff)
                let bLow := mload(cache)
                c4 := add(shr(192,mul(aLow,mload(add(cache,32)))),mul(a4,and(bLow,0xffffffff)))
                convolutionLow := mul(aLow,bLow)
                high := mul(aRev,mload(add(cache,64)))
            }
            let laneMask := 0xffffffffffffffff
            let c0 := and(convolutionLow, laneMask)
            let c1 := and(shr(64, convolutionLow), laneMask)
            let c2 := and(shr(128, convolutionLow), laneMask)
            let c3 := shr(192, convolutionLow)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(shl(1,add(add(c0,c5),sub(bias,c8))),add(shr(1,M),1)),M)
            let o1 := mod(shl(1,add(c1,c6)),M)
            let o2 := mod(shl(1,add(add(add(c2,sub(bias,c5)),c7),c8)),M)
            let o3 := mod(shl(1,add(add(c3,sub(bias,c6)),c8)),M)
            let o4 := mod(shl(1,add(c4,sub(bias,c7))),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
            low:=outLow rev:=outRev }
            if iszero(initial) {
                let aLow:=mload(ptr) let aRev:=mload(add(ptr,32)) let bLow:=low let bRev:=rev let outLow let outRev
                
            let M := 0x7f000001
            let mask := 0xffffffff

            let convolutionLow := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(convolutionLow, laneMask)
            let c1 := and(shr(64, convolutionLow), laneMask)
            let c2 := and(shr(128, convolutionLow), laneMask)
            let c3 := shr(192, convolutionLow)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(add(c0,c5),sub(bias,c8)),M)
            let o1 := mod(add(c1,c6),M)
            let o2 := mod(add(add(add(c2,sub(bias,c5)),c7),c8),M)
            let o3 := mod(add(add(c3,sub(bias,c6)),c8),M)
            let o4 := mod(add(c4,sub(bias,c7)),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
                low:=outLow rev:=outRev
            }
            mstore(ptr,low) mstore(add(ptr,32),rev)
            { let aLow:=al let aRev:=ar let bLow:=al let bRev:=ar let outLow let outRev
                
            let M := 0x7f000001
            let mask := 0xffffffff

            let convolutionLow := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(convolutionLow, laneMask)
            let c1 := and(shr(64, convolutionLow), laneMask)
            let c2 := and(shr(128, convolutionLow), laneMask)
            let c3 := shr(192, convolutionLow)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(add(c0,c5),sub(bias,c8)),M)
            let o1 := mod(add(c1,c6),M)
            let o2 := mod(add(add(add(c2,sub(bias,c5)),c7),c8),M)
            let o3 := mod(add(add(c3,sub(bias,c6)),c8),M)
            let o4 := mod(add(c4,sub(bias,c7)),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
                mstore(pointPtr,outLow) mstore(add(pointPtr,32),outRev)
            }
        }
    }
    function _eqForms(uint256 aLow, uint256 aRev, uint256[4] memory cache) internal pure returns (uint256 outLow,uint256 outRev) {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let mask := 0xffffffff

            let low
            let high
            let c4
            {
                let a0 := mod(add(and(aLow,0xffffffff),shr(1,M)),M)
                aLow := or(and(aLow,not(0xffffffff)),a0)
                let a4 := and(aRev,0xffffffff)
                let bLow := mload(cache)
                c4 := add(shr(192,mul(aLow,mload(add(cache,32)))),mul(a4,and(bLow,0xffffffff)))
                low := mul(aLow,bLow)
                high := mul(aRev,mload(add(cache,64)))
            }
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(shl(1,add(add(c0,c5),sub(bias,c8))),add(shr(1,M),1)),M)
            let o1 := mod(shl(1,add(c1,c6)),M)
            let o2 := mod(shl(1,add(add(add(c2,sub(bias,c5)),c7),c8)),M)
            let o3 := mod(shl(1,add(add(c3,sub(bias,c6)),c8)),M)
            let o4 := mod(shl(1,add(c4,sub(bias,c7))),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        }
    }
    function _mulForms(uint256 aLow,uint256 aRev,uint256 bLow,uint256 bRev) internal pure returns (uint256 outLow,uint256 outRev) {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let mask := 0xffffffff

            let low := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(add(c0,c5),sub(bias,c8)),M)
            let o1 := mod(add(c1,c6),M)
            let o2 := mod(add(add(add(c2,sub(bias,c5)),c7),c8),M)
            let o3 := mod(add(add(c3,sub(bias,c6)),c8),M)
            let o4 := mod(add(c4,sub(bias,c7)),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        }
    }
    function _eqCached(uint256 a,uint256[4] memory cache) internal pure returns(uint256 out) {
        (uint256 al,uint256 ar)=_unpackForms(a); (uint256 low,uint256 rev)=_eqForms(al,ar,cache);
        assembly ("memory-safe") { out := or(or(or(shl(224, and(low,0xffffffff)), shl(192, and(shr(64,low),0xffffffff))), or(shl(160, and(shr(128,low),0xffffffff)), shl(128, shr(192,low)))), shl(96, and(rev,0xffffffff))) }
    }
    function _stateAt(uint256[18] memory state,uint256 index) private pure returns(uint256 ptr) {
        assembly ("memory-safe") {ptr := add(state,shl(6,index))}
    }
    function _initialEqAt(uint256 ptr,uint256 a,uint256[4] memory cache) private pure {
        (uint256 al,uint256 ar)=_unpackForms(a); (uint256 low,uint256 rev)=_eqForms(al,ar,cache);
        assembly ("memory-safe") {mstore(ptr,low) mstore(add(ptr,32),rev)}
    }
    function _accEqAt(uint256 ptr,uint256 a,uint256[4] memory cache) private pure {
        assembly("memory-safe") {
            let termLow let termRev
            {
                let aLow let aRev
                { 
            let a0:=shr(224,a) let a1:=and(shr(192,a),0xffffffff) let a2:=and(shr(160,a),0xffffffff) let a3:=and(shr(128,a),0xffffffff) let a4:=and(shr(96,a),0xffffffff)
            aLow:=or(or(a0,shl(64,a1)),or(shl(128,a2),shl(192,a3)))
            aRev:=or(or(a4,shl(64,a3)),or(shl(128,a2),shl(192,a1)))
         }
                let outLow let outRev
                
            let M := 0x7f000001
            let mask := 0xffffffff

            let low
            let high
            let c4
            {
                let a0 := mod(add(and(aLow,0xffffffff),shr(1,M)),M)
                aLow := or(and(aLow,not(0xffffffff)),a0)
                let a4 := and(aRev,0xffffffff)
                let bLow := mload(cache)
                c4 := add(shr(192,mul(aLow,mload(add(cache,32)))),mul(a4,and(bLow,0xffffffff)))
                low := mul(aLow,bLow)
                high := mul(aRev,mload(add(cache,64)))
            }
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(shl(1,add(add(c0,c5),sub(bias,c8))),add(shr(1,M),1)),M)
            let o1 := mod(shl(1,add(c1,c6)),M)
            let o2 := mod(shl(1,add(add(add(c2,sub(bias,c5)),c7),c8)),M)
            let o3 := mod(shl(1,add(add(c3,sub(bias,c6)),c8)),M)
            let o4 := mod(shl(1,add(c4,sub(bias,c7))),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
                termLow:=outLow termRev:=outRev
            }
            {
                let aLow:=mload(ptr) let aRev:=mload(add(ptr,32)) let bLow:=termLow let bRev:=termRev let outLow let outRev
                
            let M := 0x7f000001
            let mask := 0xffffffff

            let low := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let bias := shl(40, M)
            let o0 := mod(add(add(c0,c5),sub(bias,c8)),M)
            let o1 := mod(add(c1,c6),M)
            let o2 := mod(add(add(add(c2,sub(bias,c5)),c7),c8),M)
            let o3 := mod(add(add(c3,sub(bias,c6)),c8),M)
            let o4 := mod(add(c4,sub(bias,c7)),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
                mstore(ptr,outLow) mstore(add(ptr,32),outRev)
            }
        }
    }
    function _packAt(uint256 ptr) private pure returns(uint256) {
        uint256 low;uint256 rev;
        assembly ("memory-safe") {low := mload(ptr) rev := mload(add(ptr,32))}
        return _packForms(low,rev);
    }



    function _prepare(uint256 q,uint256[4] memory cache) internal pure {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let q0 := and(shr(224,q),0xffffffff)
            let q1 := and(shr(192,q),0xffffffff)
            let q2 := and(shr(160,q),0xffffffff)
            let q3 := and(shr(128,q),0xffffffff)
            let q4 := and(shr(96,q),0xffffffff)
            q0 := mod(add(q0,shr(1,M)),M)
            let low := or(or(q0,shl(64,q1)),or(shl(128,q2),shl(192,q3)))
            mstore(cache,low)
            mstore(add(cache,32),or(shr(64,low),shl(192,q4)))
            mstore(add(cache,64),or(or(q4,shl(64,q3)),or(shl(128,q2),shl(192,q1))))
        }
    }
    function _eqTerm(uint256 a,uint256 b) internal pure returns(uint256) {uint256[4] memory cache;_prepare(b,cache);return _eqCached(a,cache);}
    function _packForms(uint256 low,uint256 rev) private pure returns(uint256 out) {assembly ("memory-safe") {out := or(or(or(shl(224, and(low,0xffffffff)), shl(192, and(shr(64,low),0xffffffff))), or(shl(160, and(shr(128,low),0xffffffff)), shl(128, shr(192,low)))), shl(96, and(rev,0xffffffff)))}}
    function _evaluateFixedEqTermsBlobRaw(
        bytes calldata blob,
        uint256 statementPointOffset,
        uint256 initialOodPoint,
        uint256 round0OodPoint,
        uint256 round1OodPoint,
        uint256 round2OodPoint,
        uint256[] memory fullPoint
    )
        internal
        pure
        returns (
            uint256 statementEq,
            uint256 initialEq,
            uint256 round0Eq,
            uint256 round1Eq,
            uint256 round2Eq
        )
    {










        uint256 pointBase;
        uint256[18] memory state;
        uint256[4] memory cache;
        _setPoint(_stateAt(state,8),round2OodPoint);
        _setPoint(_stateAt(state,7),round1OodPoint);
        _setPoint(_stateAt(state,6),round0OodPoint);
        _setPoint(_stateAt(state,5),initialOodPoint);
        assembly ("memory-safe") {
            pointBase := add(fullPoint, 0x20)
        }

        unchecked {
            {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    q := mload(add(pointBase, 672))
                    statementPointValue := and(
                        calldataload(add(add(blob.offset, statementPointOffset), 420)),
                        not(sub(shl(96, 1), 1))
                    )
                }
                _prepare(q,cache);
                _initialEqAt(_stateAt(state,0),statementPointValue,cache);
                _pointEq(_stateAt(state,1),_stateAt(state,5),cache,true);
                _pointEq(_stateAt(state,2),_stateAt(state,6),cache,true);
                _pointEq(_stateAt(state,3),_stateAt(state,7),cache,true);
                _pointEq(_stateAt(state,4),_stateAt(state,8),cache,true);
            }
            for (uint256 i = 21; i > 0; --i) {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    let idx := sub(i, 1)
                    q := mload(add(pointBase, shl(5, idx)))
                    statementPointValue := and(
                        calldataload(add(add(blob.offset, statementPointOffset), mul(20, idx))),
                        not(sub(shl(96, 1), 1))
                    )
                }

                _prepare(q,cache);
                _accEqAt(_stateAt(state,0),statementPointValue,cache);
                _pointEq(_stateAt(state,1),_stateAt(state,5),cache,false);

                if (i > 4) {
                    _pointEq(_stateAt(state,2),_stateAt(state,6),cache,false);
                    if (i > 8) {
                        _pointEq(_stateAt(state,3),_stateAt(state,7),cache,false);
                        if (i > 12) {
                            _pointEq(_stateAt(state,4),_stateAt(state,8),cache,false);
                        }
                    }
                }
            }
        }
        statementEq = _packAt(_stateAt(state,0));
        initialEq = _packAt(_stateAt(state,1));
        round0Eq = _packAt(_stateAt(state,2));
        round1Eq = _packAt(_stateAt(state,3));
        round2Eq = _packAt(_stateAt(state,4));
    }
}
contract KoalaBearEqPersistentStatementHarness {
    function mul(uint256 a, uint256 b) external pure returns (uint256) {
        return KoalaBearPackedField.mul(a, b);
    }

    function square(uint256 a) external pure returns (uint256) {
        return KoalaBearExt5.square(a);
    }

    function eq(uint256 a, uint256 b) external pure returns (uint256) {
        return KoalaBearEqPersistentStatement._eqTerm(a, b);
    }

    function squares(uint256 a, uint256 n) external view returns (uint256 used, uint256 result) {
        uint256 start = gasleft();
        result = a;
        for (uint256 i; i < n; ++i) {
            result = KoalaBearExt5.square(result);
        }
        used = start - gasleft();
    }

    function prepare(bytes calldata statement, uint256[4] memory ood, uint256[] memory point)
        external
        view
        returns (uint256 used, uint256[5] memory result)
    {
        require(statement.length == 440 && point.length == 22, "SHAPE");
        uint256 start = gasleft();
        (result[0], result[1], result[2], result[3], result[4]) =
            KoalaBearEqPersistentStatement._evaluateFixedEqTermsBlobRaw(
                statement, 0, ood[0], ood[1], ood[2], ood[3], point
            );
        used = start - gasleft();
    }
}
library BabyBearEqPersistentStatement {

    function _unpackForms(uint256 a) private pure returns(uint256 low,uint256 rev) {
        assembly("memory-safe") {
            let a0:=shr(224,a) let a1:=and(shr(192,a),0xffffffff) let a2:=and(shr(160,a),0xffffffff) let a3:=and(shr(128,a),0xffffffff) let a4:=and(shr(96,a),0xffffffff)
            low:=or(or(a0,shl(64,a1)),or(shl(128,a2),shl(192,a3)))
            rev:=or(or(a4,shl(64,a3)),or(shl(128,a2),shl(192,a1)))
        }
    }
    function _setPoint(uint256 ptr,uint256 a) private pure { (uint256 low,uint256 rev)=_unpackForms(a); assembly("memory-safe"){mstore(ptr,low) mstore(add(ptr,32),rev)} }
    function _pointEq(uint256 ptr,uint256 pointPtr,uint256[4] memory cache,bool initial) private pure {
        uint256 al;uint256 ar;assembly("memory-safe"){al:=mload(pointPtr) ar:=mload(add(pointPtr,32))}
        (uint256 low,uint256 rev)=_eqForms(al,ar,cache);
        if(!initial){uint256 sl;uint256 sr;assembly("memory-safe"){sl:=mload(ptr) sr:=mload(add(ptr,32))} (low,rev)=_mulForms(sl,sr,low,rev);}
        assembly("memory-safe"){mstore(ptr,low) mstore(add(ptr,32),rev)}
        (low,rev)=_mulForms(al,ar,al,ar);
        assembly("memory-safe"){mstore(pointPtr,low) mstore(add(pointPtr,32),rev)}
    }
    function _eqForms(uint256 aLow, uint256 aRev, uint256[4] memory cache) internal pure returns (uint256 outLow,uint256 outRev) {
        assembly ("memory-safe") {
            let M := 0x78000001
            let mask := 0xffffffff

            let low
            let high
            let c4
            {
                let a0 := mod(add(and(aLow,0xffffffff),shr(1,M)),M)
                aLow := or(and(aLow,not(0xffffffff)),a0)
                let a4 := and(aRev,0xffffffff)
                let bLow := mload(cache)
                c4 := add(shr(192,mul(aLow,mload(add(cache,32)))),mul(a4,and(bLow,0xffffffff)))
                low := mul(aLow,bLow)
                high := mul(aRev,mload(add(cache,64)))
            }
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let o0 := mod(add(shl(1,add(c0, shl(1, c5))),add(shr(1,M),1)),M)
            let o1 := mod(shl(1,add(c1, shl(1, c6))),M)
            let o2 := mod(shl(1,add(c2, shl(1, c7))),M)
            let o3 := mod(shl(1,add(c3, shl(1, c8))),M)
            let o4 := mod(shl(1,c4),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        }
    }
    function _mulForms(uint256 aLow,uint256 aRev,uint256 bLow,uint256 bRev) internal pure returns (uint256 outLow,uint256 outRev) {
        assembly ("memory-safe") {
            let M := 0x78000001
            let mask := 0xffffffff

            let low := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let o0 := mod(add(c0, shl(1, c5)),M)
            let o1 := mod(add(c1, shl(1, c6)),M)
            let o2 := mod(add(c2, shl(1, c7)),M)
            let o3 := mod(add(c3, shl(1, c8)),M)
            let o4 := mod(c4,M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        }
    }
    function _eqCached(uint256 a,uint256[4] memory cache) internal pure returns(uint256 out) {
        (uint256 al,uint256 ar)=_unpackForms(a); (uint256 low,uint256 rev)=_eqForms(al,ar,cache);
        assembly ("memory-safe") { out := or(or(or(shl(224, and(low,0xffffffff)), shl(192, and(shr(64,low),0xffffffff))), or(shl(160, and(shr(128,low),0xffffffff)), shl(128, shr(192,low)))), shl(96, and(rev,0xffffffff))) }
    }
    function _stateAt(uint256[18] memory state,uint256 index) private pure returns(uint256 ptr) {
        assembly ("memory-safe") {ptr := add(state,shl(6,index))}
    }
    function _initialEqAt(uint256 ptr,uint256 a,uint256[4] memory cache) private pure {
        (uint256 al,uint256 ar)=_unpackForms(a); (uint256 low,uint256 rev)=_eqForms(al,ar,cache);
        assembly ("memory-safe") {mstore(ptr,low) mstore(add(ptr,32),rev)}
    }
    function _accEqAt(uint256 ptr,uint256 a,uint256[4] memory cache) private pure {
        assembly("memory-safe") {
            let termLow let termRev
            {
                let aLow let aRev
                { 
            let a0:=shr(224,a) let a1:=and(shr(192,a),0xffffffff) let a2:=and(shr(160,a),0xffffffff) let a3:=and(shr(128,a),0xffffffff) let a4:=and(shr(96,a),0xffffffff)
            aLow:=or(or(a0,shl(64,a1)),or(shl(128,a2),shl(192,a3)))
            aRev:=or(or(a4,shl(64,a3)),or(shl(128,a2),shl(192,a1)))
         }
                let outLow let outRev
                
            let M := 0x78000001
            let mask := 0xffffffff

            let low
            let high
            let c4
            {
                let a0 := mod(add(and(aLow,0xffffffff),shr(1,M)),M)
                aLow := or(and(aLow,not(0xffffffff)),a0)
                let a4 := and(aRev,0xffffffff)
                let bLow := mload(cache)
                c4 := add(shr(192,mul(aLow,mload(add(cache,32)))),mul(a4,and(bLow,0xffffffff)))
                low := mul(aLow,bLow)
                high := mul(aRev,mload(add(cache,64)))
            }
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let o0 := mod(add(shl(1,add(c0, shl(1, c5))),add(shr(1,M),1)),M)
            let o1 := mod(shl(1,add(c1, shl(1, c6))),M)
            let o2 := mod(shl(1,add(c2, shl(1, c7))),M)
            let o3 := mod(shl(1,add(c3, shl(1, c8))),M)
            let o4 := mod(shl(1,c4),M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
                termLow:=outLow termRev:=outRev
            }
            {
                let aLow:=mload(ptr) let aRev:=mload(add(ptr,32)) let bLow:=termLow let bRev:=termRev let outLow let outRev
                
            let M := 0x78000001
            let mask := 0xffffffff

            let low := mul(aLow,bLow)
            let high := mul(aRev,bRev)
            let c4 := add(shr(192,mul(aLow,or(shr(64,bLow),shl(192,and(bRev,0xffffffff))))),mul(and(aRev,0xffffffff),and(bLow,0xffffffff)))
            let laneMask := 0xffffffffffffffff
            let c0 := and(low, laneMask)
            let c1 := and(shr(64, low), laneMask)
            let c2 := and(shr(128, low), laneMask)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), laneMask)
            let c7 := and(shr(64, high), laneMask)
            let c8 := and(high, laneMask)
            let o0 := mod(add(c0, shl(1, c5)),M)
            let o1 := mod(add(c1, shl(1, c6)),M)
            let o2 := mod(add(c2, shl(1, c7)),M)
            let o3 := mod(add(c3, shl(1, c8)),M)
            let o4 := mod(c4,M)
            outLow := or(or(o0,shl(64,o1)),or(shl(128,o2),shl(192,o3)))
            outRev := or(or(o4,shl(64,o3)),or(shl(128,o2),shl(192,o1)))
        
                mstore(ptr,outLow) mstore(add(ptr,32),outRev)
            }
        }
    }
    function _packAt(uint256 ptr) private pure returns(uint256) {
        uint256 low;uint256 rev;
        assembly ("memory-safe") {low := mload(ptr) rev := mload(add(ptr,32))}
        return _packForms(low,rev);
    }



    function _prepare(uint256 q,uint256[4] memory cache) internal pure {
        assembly ("memory-safe") {
            let M := 0x78000001
            let q0 := and(shr(224,q),0xffffffff)
            let q1 := and(shr(192,q),0xffffffff)
            let q2 := and(shr(160,q),0xffffffff)
            let q3 := and(shr(128,q),0xffffffff)
            let q4 := and(shr(96,q),0xffffffff)
            q0 := mod(add(q0,shr(1,M)),M)
            let low := or(or(q0,shl(64,q1)),or(shl(128,q2),shl(192,q3)))
            mstore(cache,low)
            mstore(add(cache,32),or(shr(64,low),shl(192,q4)))
            mstore(add(cache,64),or(or(q4,shl(64,q3)),or(shl(128,q2),shl(192,q1))))
        }
    }
    function _eqTerm(uint256 a,uint256 b) internal pure returns(uint256) {uint256[4] memory cache;_prepare(b,cache);return _eqCached(a,cache);}
    function _packForms(uint256 low,uint256 rev) private pure returns(uint256 out) {assembly ("memory-safe") {out := or(or(or(shl(224, and(low,0xffffffff)), shl(192, and(shr(64,low),0xffffffff))), or(shl(160, and(shr(128,low),0xffffffff)), shl(128, shr(192,low)))), shl(96, and(rev,0xffffffff)))}}
    function _evaluateFixedEqTermsBlobRaw(
        bytes calldata blob,
        uint256 statementPointOffset,
        uint256 initialOodPoint,
        uint256 round0OodPoint,
        uint256 round1OodPoint,
        uint256 round2OodPoint,
        uint256[] memory fullPoint
    )
        internal
        pure
        returns (
            uint256 statementEq,
            uint256 initialEq,
            uint256 round0Eq,
            uint256 round1Eq,
            uint256 round2Eq
        )
    {










        uint256 pointBase;
        uint256[18] memory state;
        uint256[4] memory cache;
        _setPoint(_stateAt(state,8),round2OodPoint);
        _setPoint(_stateAt(state,7),round1OodPoint);
        _setPoint(_stateAt(state,6),round0OodPoint);
        _setPoint(_stateAt(state,5),initialOodPoint);
        assembly ("memory-safe") {
            pointBase := add(fullPoint, 0x20)
        }

        unchecked {
            {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    q := mload(add(pointBase, 672))
                    statementPointValue := and(
                        calldataload(add(add(blob.offset, statementPointOffset), 420)),
                        not(sub(shl(96, 1), 1))
                    )
                }
                _prepare(q,cache);
                _initialEqAt(_stateAt(state,0),statementPointValue,cache);
                _pointEq(_stateAt(state,1),_stateAt(state,5),cache,true);
                _pointEq(_stateAt(state,2),_stateAt(state,6),cache,true);
                _pointEq(_stateAt(state,3),_stateAt(state,7),cache,true);
                _pointEq(_stateAt(state,4),_stateAt(state,8),cache,true);
            }
            for (uint256 i = 21; i > 0; --i) {
                uint256 q;
                uint256 statementPointValue;
                assembly ("memory-safe") {
                    let idx := sub(i, 1)
                    q := mload(add(pointBase, shl(5, idx)))
                    statementPointValue := and(
                        calldataload(add(add(blob.offset, statementPointOffset), mul(20, idx))),
                        not(sub(shl(96, 1), 1))
                    )
                }

                _prepare(q,cache);
                _accEqAt(_stateAt(state,0),statementPointValue,cache);
                _pointEq(_stateAt(state,1),_stateAt(state,5),cache,false);

                if (i > 4) {
                    _pointEq(_stateAt(state,2),_stateAt(state,6),cache,false);
                    if (i > 8) {
                        _pointEq(_stateAt(state,3),_stateAt(state,7),cache,false);
                        if (i > 12) {
                            _pointEq(_stateAt(state,4),_stateAt(state,8),cache,false);
                        }
                    }
                }
            }
        }
        statementEq = _packAt(_stateAt(state,0));
        initialEq = _packAt(_stateAt(state,1));
        round0Eq = _packAt(_stateAt(state,2));
        round1Eq = _packAt(_stateAt(state,3));
        round2Eq = _packAt(_stateAt(state,4));
    }
}
contract BabyBearEqPersistentStatementHarness {
    function mul(uint256 a, uint256 b) external pure returns (uint256) {
        return BabyBearPackedField.mul(a, b);
    }

    function square(uint256 a) external pure returns (uint256) {
        return BabyBearBenchField.square(a);
    }

    function eq(uint256 a, uint256 b) external pure returns (uint256) {
        return BabyBearEqPersistentStatement._eqTerm(a, b);
    }

    function squares(uint256 a, uint256 n) external view returns (uint256 used, uint256 result) {
        uint256 start = gasleft();
        result = a;
        for (uint256 i; i < n; ++i) {
            result = BabyBearBenchField.square(result);
        }
        used = start - gasleft();
    }

    function prepare(bytes calldata statement, uint256[4] memory ood, uint256[] memory point)
        external
        view
        returns (uint256 used, uint256[5] memory result)
    {
        require(statement.length == 440 && point.length == 22, "SHAPE");
        uint256 start = gasleft();
        (result[0], result[1], result[2], result[3], result[4]) =
            BabyBearEqPersistentStatement._evaluateFixedEqTermsBlobRaw(
                statement, 0, ood[0], ood[1], ood[2], ood[3], point
            );
        used = start - gasleft();
    }
}
