// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// Generated by script/babybear/generate_select_variants.py.
// Native core SHA-256: 221d61a7a31eb32af199eaeabb7187e49309d229d91b1ca9733e28855ea79d78
import { KoalaBear } from "../../src/field/KoalaBear.sol";
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";

library BabyBearBenchField {
    uint256 internal constant MODULUS = 0x78000001;
    uint256 internal constant ONE = uint256(1) << 224;

    function add(uint256 a, uint256 b) internal pure returns (uint256 out) {
        assembly ("memory-safe") {
            let modulus := 0x78000001
            let sum := add(a, b)
            let highBits :=
                and(
                    add(sum, 0x07ffffff07ffffff07ffffff07ffffff07ffffff000000000000000000000000),
                    0x8000000080000000800000008000000080000000000000000000000000000000
                )
            out := and(
                sub(sum, mul(shr(31, highBits), modulus)),
                0xffffffffffffffffffffffffffffffffffffffff000000000000000000000000
            )
        }
    }

    function sub(uint256 a, uint256 b) internal pure returns (uint256 out) {
        assembly ("memory-safe") {
            let modulus := 0x78000001
            let tmp :=
                sub(add(a, 0x7800000178000001780000017800000178000001000000000000000000000000), b)
            let highBits :=
                and(
                    add(tmp, 0x07ffffff07ffffff07ffffff07ffffff07ffffff000000000000000000000000),
                    0x8000000080000000800000008000000080000000000000000000000000000000
                )
            out := and(
                sub(tmp, mul(shr(31, highBits), modulus)),
                0xffffffffffffffffffffffffffffffffffffffff000000000000000000000000
            )
        }
    }

    function mul(uint256 a, uint256 b) internal pure returns (uint256 out) {
        assembly ("memory-safe") {
            let M := 0x78000001
            let mask := 0xffffffff

            let a0 := shr(224, a)
            let a1 := and(shr(192, a), mask)
            let a2 := and(shr(160, a), mask)
            let a3 := and(shr(128, a), mask)
            let a4 := and(shr(96, a), mask)

            let b0 := shr(224, b)
            let b1 := and(shr(192, b), mask)
            let b2 := and(shr(160, b), mask)
            let b3 := and(shr(128, b), mask)
            let b4 := and(shr(96, b), mask)

            let c0 := mul(a0, b0)
            let c1 := add(mul(a0, b1), mul(a1, b0))
            let c2 := add(add(mul(a0, b2), mul(a1, b1)), mul(a2, b0))
            let c3 := add(add(add(mul(a0, b3), mul(a1, b2)), mul(a2, b1)), mul(a3, b0))
            let c4 :=
                add(add(add(add(mul(a0, b4), mul(a1, b3)), mul(a2, b2)), mul(a3, b1)), mul(a4, b0))
            let c5 := add(add(add(mul(a1, b4), mul(a2, b3)), mul(a3, b2)), mul(a4, b1))
            let c6 := add(add(mul(a2, b4), mul(a3, b3)), mul(a4, b2))
            let c7 := add(mul(a3, b4), mul(a4, b3))
            let c8 := mul(a4, b4)
            out := or(
                or(
                    or(
                        shl(224, mod(add(c0, shl(1, c5)), M)),
                        shl(192, mod(add(c1, shl(1, c6)), M))
                    ),
                    or(shl(160, mod(add(c2, shl(1, c7)), M)), shl(128, mod(add(c3, shl(1, c8)), M)))
                ),
                shl(96, mod(c4, M))
            )
        }
    }

    function square(uint256 a) internal pure returns (uint256 out) {
        assembly ("memory-safe") {
            let M := 0x78000001
            let mask := 0xffffffff

            let a0 := shr(224, a)
            let a1 := and(shr(192, a), mask)
            let a2 := and(shr(160, a), mask)
            let a3 := and(shr(128, a), mask)
            let a4 := and(shr(96, a), mask)

            let a0a0 := mul(a0, a0)
            let a0a1 := mul(a0, a1)
            let a0a2 := mul(a0, a2)
            let a0a3 := mul(a0, a3)
            let a0a4 := mul(a0, a4)
            let a1a1 := mul(a1, a1)
            let a1a2 := mul(a1, a2)
            let a1a3 := mul(a1, a3)
            let a1a4 := mul(a1, a4)
            let a2a2 := mul(a2, a2)
            let a2a3 := mul(a2, a3)
            let a2a4 := mul(a2, a4)
            let a3a3 := mul(a3, a3)
            let a3a4 := mul(a3, a4)
            let a4a4 := mul(a4, a4)

            let c0 := a0a0
            let c1 := shl(1, a0a1)
            let c2 := add(shl(1, a0a2), a1a1)
            let c3 := add(shl(1, a0a3), shl(1, a1a2))
            let c4 := add(add(shl(1, a0a4), shl(1, a1a3)), a2a2)
            let c5 := add(shl(1, a1a4), shl(1, a2a3))
            let c6 := add(shl(1, a2a4), a3a3)
            let c7 := shl(1, a3a4)
            let c8 := a4a4
            out := or(
                or(
                    or(
                        shl(224, mod(add(c0, shl(1, c5)), M)),
                        shl(192, mod(add(c1, shl(1, c6)), M))
                    ),
                    or(shl(160, mod(add(c2, shl(1, c7)), M)), shl(128, mod(add(c3, shl(1, c8)), M)))
                ),
                shl(96, mod(c4, M))
            )
        }
    }
}

