#!/usr/bin/env python3
"""Export Poseidon AIR constants and differential cases from the LeanVM Python verifier."""

import argparse
import hashlib
import json
from pathlib import Path
import random
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--leanvm", type=Path)
    args = parser.parse_args()
    project = Path(__file__).resolve().parents[1]
    leanvm = args.leanvm or project.parent / "leanVM"
    reference = leanvm / "crates/lean_prover/python-verifier"
    sys.path.insert(0, str(reference))
    import primitives as p
    import verifier as v

    names = [
        ("INITIAL", "POSEIDON_AIR_INITIAL_CONSTANTS"),
        ("FINAL", "POSEIDON_AIR_FINAL_CONSTANTS"),
        ("SPARSE_FIRST_RC", "POSEIDON_AIR_SPARSE_FIRST_RC"),
        ("SPARSE_M_I", "POSEIDON_AIR_SPARSE_M_I"),
        ("SPARSE_SCALAR_RC", "POSEIDON_AIR_SPARSE_SCALAR_RC"),
        ("SPARSE_FIRST_ROW", "POSEIDON_AIR_SPARSE_FIRST_ROW"),
        ("SPARSE_V", "POSEIDON_AIR_SPARSE_V"),
    ]

    def flatten(value):
        if isinstance(value, p.Fp):
            return [value.value]
        return [x for child in value for x in flatten(child)]

    constants = []
    declarations = []
    for short, name in names:
        declarations.append(f"    uint256 internal constant {short} = {len(constants)};")
        constants.extend(flatten(getattr(p, name)))
    encoded = b"".join(value.to_bytes(4, "big") for value in constants)
    solidity = "\n".join([
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.28;",
        "",
        "// Generated by script/generate_leanvm_air_vectors.py. Offsets count four-byte words.",
        "library LeanVmPoseidonAirConstants {",
        *declarations,
        "",
        "    function values() internal pure returns (bytes memory) {",
        f'        return hex"{encoded.hex()}";',
        "    }",
        "}",
        "",
    ])
    (project / "src/leanvm/LeanVmPoseidonAirConstants.sol").write_text(solidity)

    rng = random.Random(0x4C45414E564D)

    def random_ef():
        return p.EF([p.Fp(rng.randrange(p.P)) for _ in range(5)])

    def encode(values):
        return [[c.value for c in value.c] for value in values]

    counts = {"execution": 14, "extension": 35, "poseidon": 96}
    cases = []
    metadata = []
    for table in v.TABLES:
        count = counts[table.name]
        metadata.append({"table": table.name, "columns": list(table.columns), "shifts": table.n_shift, "constraints": count})

        def add_case(label, flat, shift, alphas, beta):
            evaluator = v.ConstraintEvaluator(flat, shift, alphas, table.columns)
            table.air_constraints_fn(evaluator, beta)
            assert evaluator.i == count, (table.name, evaluator.i, count)
            cases.append({
                "id": label, "table": table.name, "flat": encode(flat), "shift": encode(shift),
                "alphas": encode(alphas), "beta_eq": encode(beta), "expected": encode([evaluator.accumulator])[0],
            })

        for value in [0, 1, p.P - 1]:
            add_case(f"constant-{value}", [p.EF(value)] * table.n_columns, [p.EF(value)] * table.n_shift,
                     [random_ef() for _ in range(count)], [random_ef() for _ in range(16)])
        for coordinate in range(5):
            basis = p.EF([p.Fp(int(i == coordinate)) for i in range(5)])
            add_case(f"basis-{coordinate}", [basis] * table.n_columns, [basis] * table.n_shift,
                     [random_ef() for _ in range(count)], [random_ef() for _ in range(16)])
        for sample in range(4):
            add_case(f"random-{sample}", [random_ef() for _ in range(table.n_columns)],
                     [random_ef() for _ in range(table.n_shift)], [random_ef() for _ in range(count)],
                     [random_ef() for _ in range(16)])
        flat = [random_ef() for _ in range(table.n_columns)]
        shift = [random_ef() for _ in range(table.n_shift)]
        beta = [random_ef() for _ in range(16)]
        boundaries = {
            "execution": list(range(14)),
            "extension": [0, 1, 2, 6, 7, 11, 12, 16, 17, 21, 22, 26, 27, 31, 32, 33, 34],
            "poseidon": [0, 1, 2, 6, 7, 11, 12, 27, 28, 43, 44, 63, 64, 79, 80, 81, 86, 87, 94, 95],
        }[table.name]
        for constraint in boundaries:
            alphas = [p.ZERO] * count
            alphas[constraint] = p.ONE
            add_case(f"constraint-{constraint}", flat, shift, alphas, beta)

    document = {
        "format": "leanvm-air-quintic-v1",
        "source_sha256": {name: hashlib.sha256((reference / name).read_bytes()).hexdigest()
                          for name in ["primitives.py", "verifier.py"]},
        "poseidon_constants_sha256": hashlib.sha256(encoded).hexdigest(),
        "tables": metadata,
        "vectors": cases,
    }
    destination = project / "testdata/leanvm_air/vectors.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(document, indent=2) + "\n")
    print(f"Exported {len(cases)} AIR vectors and {len(constants)} Poseidon constants")


if __name__ == "__main__":
    main()
