// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/generate_select_forms.py.
// Each accumulator is two words with four canonical coefficients in 64-bit lanes.
// The four-term convolution lanes stay below 2^64. Final coefficient reductions
// precede every repack, including when scalar is in [0,2*M-2].
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import { BabyBearBenchField, BabyBearSelectPrepackedCombined } from "./BabyBearSelectVariants.sol";
import { BabyBearPackedField, KoalaBearPackedField } from "./BabyBearPackedFields.sol";

library KoalaBearSelectForms {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let bias := shl(40, M)
            let o0 :=
                mod(add(and(aLow, 0xffffffff), mul(scalar, add(add(c0, c5), sub(bias, c8)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, c6))), M)
            let o2 :=
                mod(
                    add(
                        and(shr(128, aLow), 0xffffffff),
                        mul(scalar, add(add(add(c2, sub(bias, c5)), c7), c8))
                    ),
                    M
                )
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(add(c3, sub(bias, c6)), c8))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, add(c4, sub(bias, c7)))), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x7f000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x7f000001)
                    ptr := sub(ptr, 96)
                }
                (low, rev) = _multiply(low, rev, ptr, current + (0x7f000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x7f000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x7f000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x7f000001)
                    current1 := mulmod(current1, current1, 0x7f000001)
                    ptr := sub(ptr, 96)
                }
                (low0, rev0) = _multiply(low0, rev0, ptr, current0 + (0x7f000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, ptr, current1 + (0x7f000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return KoalaBearExt5.add(KoalaBearExt5.mul(total, challenge), weight);
    }
}

contract KoalaBearSelectFormsHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = KoalaBearSelectForms._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return KoalaBearSelectForms._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = KoalaBearSelectForms._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = KoalaBearSelectForms._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = KoalaBearSelectForms._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectForms {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low, rev) = _multiply(low, rev, ptr, current + (0x78000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x78000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x78000001)
                    current1 := mulmod(current1, current1, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low0, rev0) = _multiply(low0, rev0, ptr, current0 + (0x78000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, ptr, current1 + (0x78000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectFormsHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectForms._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectForms._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectForms._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectForms._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectForms._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library KoalaBearSelectFormsPackedHorner {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let bias := shl(40, M)
            let o0 :=
                mod(add(and(aLow, 0xffffffff), mul(scalar, add(add(c0, c5), sub(bias, c8)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, c6))), M)
            let o2 :=
                mod(
                    add(
                        and(shr(128, aLow), 0xffffffff),
                        mul(scalar, add(add(add(c2, sub(bias, c5)), c7), c8))
                    ),
                    M
                )
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(add(c3, sub(bias, c6)), c8))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, add(c4, sub(bias, c7)))), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x7f000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x7f000001)
                    ptr := sub(ptr, 96)
                }
                (low, rev) = _multiply(low, rev, ptr, current + (0x7f000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x7f000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x7f000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x7f000001)
                    current1 := mulmod(current1, current1, 0x7f000001)
                    ptr := sub(ptr, 96)
                }
                (low0, rev0) = _multiply(low0, rev0, ptr, current0 + (0x7f000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, ptr, current1 + (0x7f000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return KoalaBearPackedField.add(KoalaBearPackedField.mul(total, challenge), weight);
    }
}

contract KoalaBearSelectFormsPackedHornerHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = KoalaBearSelectFormsPackedHorner._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return KoalaBearSelectFormsPackedHorner._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = KoalaBearSelectFormsPackedHorner._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = KoalaBearSelectFormsPackedHorner._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = KoalaBearSelectFormsPackedHorner._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library KoalaBearSelectFormsSharedPair {
    function _multiply(
        uint256 aLow,
        uint256 aRev,
        uint256 bLow,
        uint256 bMid,
        uint256 bRev,
        uint256 scalar
    ) private pure returns (uint256 lowOut, uint256 revOut) {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let c4 :=
                add(shr(192, mul(aLow, bMid)), mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff)))
            let low := mul(aLow, bLow)
            let high := mul(aRev, bRev)
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let bias := shl(40, M)
            let o0 :=
                mod(add(and(aLow, 0xffffffff), mul(scalar, add(add(c0, c5), sub(bias, c8)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, c6))), M)
            let o2 :=
                mod(
                    add(
                        and(shr(128, aLow), 0xffffffff),
                        mul(scalar, add(add(add(c2, sub(bias, c5)), c7), c8))
                    ),
                    M
                )
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(add(c3, sub(bias, c6)), c8))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, add(c4, sub(bias, c7)))), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x7f000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x7f000001)
                    ptr := sub(ptr, 96)
                }
                uint256 bLow;
                uint256 bMid;
                uint256 bRev;
                assembly ("memory-safe") {
                    bLow := mload(ptr)
                    bMid := mload(add(ptr, 32))
                    bRev := mload(add(ptr, 64))
                }
                (low, rev) = _multiply(low, rev, bLow, bMid, bRev, current + (0x7f000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x7f000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x7f000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x7f000001)
                    current1 := mulmod(current1, current1, 0x7f000001)
                    ptr := sub(ptr, 96)
                }
                uint256 bLow;
                uint256 bMid;
                uint256 bRev;
                assembly ("memory-safe") {
                    bLow := mload(ptr)
                    bMid := mload(add(ptr, 32))
                    bRev := mload(add(ptr, 64))
                }
                (low0, rev0) = _multiply(low0, rev0, bLow, bMid, bRev, current0 + (0x7f000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, bLow, bMid, bRev, current1 + (0x7f000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return KoalaBearExt5.add(KoalaBearExt5.mul(total, challenge), weight);
    }
}

contract KoalaBearSelectFormsSharedPairHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = KoalaBearSelectFormsSharedPair._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return KoalaBearSelectFormsSharedPair._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = KoalaBearSelectFormsSharedPair._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = KoalaBearSelectFormsSharedPair._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = KoalaBearSelectFormsSharedPair._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectFormsPackedHorner {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low, rev) = _multiply(low, rev, ptr, current + (0x78000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x78000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x78000001)
                    current1 := mulmod(current1, current1, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low0, rev0) = _multiply(low0, rev0, ptr, current0 + (0x78000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, ptr, current1 + (0x78000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearPackedField.add(BabyBearPackedField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectFormsPackedHornerHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectFormsPackedHorner._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectFormsPackedHorner._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectFormsPackedHorner._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectFormsPackedHorner._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectFormsPackedHorner._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectFormsSharedPair {
    function _multiply(
        uint256 aLow,
        uint256 aRev,
        uint256 bLow,
        uint256 bMid,
        uint256 bRev,
        uint256 scalar
    ) private pure returns (uint256 lowOut, uint256 revOut) {
        assembly ("memory-safe") {
            let M := 0x78000001
            let c4 :=
                add(shr(192, mul(aLow, bMid)), mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff)))
            let low := mul(aLow, bLow)
            let high := mul(aRev, bRev)
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                uint256 bLow;
                uint256 bMid;
                uint256 bRev;
                assembly ("memory-safe") {
                    bLow := mload(ptr)
                    bMid := mload(add(ptr, 32))
                    bRev := mload(add(ptr, 64))
                }
                (low, rev) = _multiply(low, rev, bLow, bMid, bRev, current + (0x78000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x78000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x78000001)
                    current1 := mulmod(current1, current1, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                uint256 bLow;
                uint256 bMid;
                uint256 bRev;
                assembly ("memory-safe") {
                    bLow := mload(ptr)
                    bMid := mload(add(ptr, 32))
                    bRev := mload(add(ptr, 64))
                }
                (low0, rev0) = _multiply(low0, rev0, bLow, bMid, bRev, current0 + (0x78000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, bLow, bMid, bRev, current1 + (0x78000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectFormsSharedPairHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectFormsSharedPair._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectFormsSharedPair._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectFormsSharedPair._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectFormsSharedPair._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectFormsSharedPair._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}
