// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
// Generated by script/babybear/select_followup_experiments.py.
// Adjacent select factors are expanded as A+B*x+C*x^2+D*x^3.
// Each accumulator is two words with four canonical coefficients in 64-bit lanes.
// The four-term convolution lanes stay below 2^64. Final coefficient reductions
// precede every repack, including when scalar is in [0,2*M-2].
import { KoalaBearExt5 } from "../../src/field/KoalaBearExt5.sol";
import {
    KoalaBearSelectPrepackedCombined,
    BabyBearBenchField,
    BabyBearSelectPrepackedCombined
} from "./BabyBearSelectVariants.sol";
import { BabyBearPackedField, KoalaBearPackedField } from "./BabyBearPackedFields.sol";

library BabyBearSelectForms {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low, rev) = _multiply(low, rev, ptr, current + (0x78000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x78000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x78000001)
                    current1 := mulmod(current1, current1, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low0, rev0) = _multiply(low0, rev0, ptr, current0 + (0x78000001 - 1));
                (low1, rev1) = _multiply(low1, rev1, ptr, current1 + (0x78000001 - 1));
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectFormsHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectForms._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectForms._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectForms._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectForms._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectForms._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectInline {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                assembly ("memory-safe") {
                    let M := 0x78000001
                    let bLow := mload(ptr)
                    let c4 :=
                        add(
                            shr(192, mul(low, mload(add(ptr, 32)))),
                            mul(and(rev, 0xffffffff), and(bLow, 0xffffffff))
                        )
                    let convLow := mul(low, bLow)
                    let high := mul(rev, mload(add(ptr, 64)))
                    let c0 := and(convLow, 0xffffffffffffffff)
                    let c1 := and(shr(64, convLow), 0xffffffffffffffff)
                    let c2 := and(shr(128, convLow), 0xffffffffffffffff)
                    let c3 := shr(192, convLow)
                    let c5 := shr(192, high)
                    let c6 := and(shr(128, high), 0xffffffffffffffff)
                    let c7 := and(shr(64, high), 0xffffffffffffffff)
                    let c8 := and(high, 0xffffffffffffffff)
                    let o0 :=
                        mod(
                            add(
                                and(low, 0xffffffff),
                                mul(add(current, 0x78000000), add(c0, shl(1, c5)))
                            ),
                            M
                        )
                    let o1 :=
                        mod(
                            add(
                                and(shr(64, low), 0xffffffff),
                                mul(add(current, 0x78000000), add(c1, shl(1, c6)))
                            ),
                            M
                        )
                    let o2 :=
                        mod(
                            add(
                                and(shr(128, low), 0xffffffff),
                                mul(add(current, 0x78000000), add(c2, shl(1, c7)))
                            ),
                            M
                        )
                    let o3 :=
                        mod(
                            add(shr(192, low), mul(add(current, 0x78000000), add(c3, shl(1, c8)))),
                            M
                        )
                    let o4 := mod(add(and(rev, 0xffffffff), mul(add(current, 0x78000000), c4)), M)
                    low := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
                    rev := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
                }
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x78000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current0 := mulmod(current0, current0, 0x78000001)
                    current1 := mulmod(current1, current1, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                assembly ("memory-safe") {
                    let M := 0x78000001
                    let bLow := mload(ptr)
                    let c4 :=
                        add(
                            shr(192, mul(low0, mload(add(ptr, 32)))),
                            mul(and(rev0, 0xffffffff), and(bLow, 0xffffffff))
                        )
                    let convLow := mul(low0, bLow)
                    let high := mul(rev0, mload(add(ptr, 64)))
                    let c0 := and(convLow, 0xffffffffffffffff)
                    let c1 := and(shr(64, convLow), 0xffffffffffffffff)
                    let c2 := and(shr(128, convLow), 0xffffffffffffffff)
                    let c3 := shr(192, convLow)
                    let c5 := shr(192, high)
                    let c6 := and(shr(128, high), 0xffffffffffffffff)
                    let c7 := and(shr(64, high), 0xffffffffffffffff)
                    let c8 := and(high, 0xffffffffffffffff)
                    let o0 :=
                        mod(
                            add(
                                and(low0, 0xffffffff),
                                mul(add(current0, 0x78000000), add(c0, shl(1, c5)))
                            ),
                            M
                        )
                    let o1 :=
                        mod(
                            add(
                                and(shr(64, low0), 0xffffffff),
                                mul(add(current0, 0x78000000), add(c1, shl(1, c6)))
                            ),
                            M
                        )
                    let o2 :=
                        mod(
                            add(
                                and(shr(128, low0), 0xffffffff),
                                mul(add(current0, 0x78000000), add(c2, shl(1, c7)))
                            ),
                            M
                        )
                    let o3 :=
                        mod(
                            add(
                                shr(192, low0),
                                mul(add(current0, 0x78000000), add(c3, shl(1, c8)))
                            ),
                            M
                        )
                    let o4 := mod(add(and(rev0, 0xffffffff), mul(add(current0, 0x78000000), c4)), M)
                    low0 := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
                    rev0 := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
                }
                assembly ("memory-safe") {
                    let M := 0x78000001
                    let bLow := mload(ptr)
                    let c4 :=
                        add(
                            shr(192, mul(low1, mload(add(ptr, 32)))),
                            mul(and(rev1, 0xffffffff), and(bLow, 0xffffffff))
                        )
                    let convLow := mul(low1, bLow)
                    let high := mul(rev1, mload(add(ptr, 64)))
                    let c0 := and(convLow, 0xffffffffffffffff)
                    let c1 := and(shr(64, convLow), 0xffffffffffffffff)
                    let c2 := and(shr(128, convLow), 0xffffffffffffffff)
                    let c3 := shr(192, convLow)
                    let c5 := shr(192, high)
                    let c6 := and(shr(128, high), 0xffffffffffffffff)
                    let c7 := and(shr(64, high), 0xffffffffffffffff)
                    let c8 := and(high, 0xffffffffffffffff)
                    let o0 :=
                        mod(
                            add(
                                and(low1, 0xffffffff),
                                mul(add(current1, 0x78000000), add(c0, shl(1, c5)))
                            ),
                            M
                        )
                    let o1 :=
                        mod(
                            add(
                                and(shr(64, low1), 0xffffffff),
                                mul(add(current1, 0x78000000), add(c1, shl(1, c6)))
                            ),
                            M
                        )
                    let o2 :=
                        mod(
                            add(
                                and(shr(128, low1), 0xffffffff),
                                mul(add(current1, 0x78000000), add(c2, shl(1, c7)))
                            ),
                            M
                        )
                    let o3 :=
                        mod(
                            add(
                                shr(192, low1),
                                mul(add(current1, 0x78000000), add(c3, shl(1, c8)))
                            ),
                            M
                        )
                    let o4 := mod(add(and(rev1, 0xffffffff), mul(add(current1, 0x78000000), c4)), M)
                    low1 := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
                    rev1 := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
                }
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectInlineHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectInline._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectInline._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectInline._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectInline._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectInline._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectSingles {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            for (uint256 i = n - 1; i > 0; --i) {
                assembly ("memory-safe") {
                    current := mulmod(current, current, 0x78000001)
                    ptr := sub(ptr, 96)
                }
                (low, rev) = _multiply(low, rev, ptr, current + (0x78000001 - 1));
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        return (
            _selectPolyEvalFixed(current0, cache, offset, n),
            _selectPolyEvalFixed(current1, cache, offset, n)
        );
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectSinglesHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectSingles._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectSingles._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectSingles._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectSingles._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectSingles._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectAssemblyLoop {
    function _multiply(uint256 aLow, uint256 aRev, uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let bLow := mload(ptr)
            let c4 :=
                add(
                    shr(192, mul(aLow, mload(add(ptr, 32)))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, mload(add(ptr, 64)))
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(and(aLow, 0xffffffff), mul(scalar, add(c0, shl(1, c5)))), M)
            let o1 := mod(add(and(shr(64, aLow), 0xffffffff), mul(scalar, add(c1, shl(1, c6)))), M)
            let o2 := mod(add(and(shr(128, aLow), 0xffffffff), mul(scalar, add(c2, shl(1, c7)))), M)
            let o3 := mod(add(shr(192, aLow), mul(scalar, add(c3, shl(1, c8)))), M)
            let o4 := mod(add(and(aRev, 0xffffffff), mul(scalar, c4)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(
        uint256 current,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256) {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low;
        uint256 rev;
        unchecked {
            (low, rev) = _initial(ptr, current + (0x78000001 - 1));
            assembly ("memory-safe") {
                for { let i := sub(n, 1) } i { i := sub(i, 1) } {
                    ptr := sub(ptr, 96)
                    current := mulmod(current, current, 0x78000001)
                    {
                        let M := 0x78000001
                        let bLow := mload(ptr)
                        let c4 :=
                            add(
                                shr(192, mul(low, mload(add(ptr, 32)))),
                                mul(and(rev, 0xffffffff), and(bLow, 0xffffffff))
                            )
                        let convLow := mul(low, bLow)
                        let high := mul(rev, mload(add(ptr, 64)))
                        let c0 := and(convLow, 0xffffffffffffffff)
                        let c1 := and(shr(64, convLow), 0xffffffffffffffff)
                        let c2 := and(shr(128, convLow), 0xffffffffffffffff)
                        let c3 := shr(192, convLow)
                        let c5 := shr(192, high)
                        let c6 := and(shr(128, high), 0xffffffffffffffff)
                        let c7 := and(shr(64, high), 0xffffffffffffffff)
                        let c8 := and(high, 0xffffffffffffffff)
                        let o0 :=
                            mod(
                                add(
                                    and(low, 0xffffffff),
                                    mul(add(current, 0x78000000), add(c0, shl(1, c5)))
                                ),
                                M
                            )
                        let o1 :=
                            mod(
                                add(
                                    and(shr(64, low), 0xffffffff),
                                    mul(add(current, 0x78000000), add(c1, shl(1, c6)))
                                ),
                                M
                            )
                        let o2 :=
                            mod(
                                add(
                                    and(shr(128, low), 0xffffffff),
                                    mul(add(current, 0x78000000), add(c2, shl(1, c7)))
                                ),
                                M
                            )
                        let o3 :=
                            mod(
                                add(
                                    shr(192, low),
                                    mul(add(current, 0x78000000), add(c3, shl(1, c8)))
                                ),
                                M
                            )
                        let o4 :=
                            mod(add(and(rev, 0xffffffff), mul(add(current, 0x78000000), c4)), M)
                        low := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
                        rev := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
                    }
                }
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 current0,
        uint256 current1,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256 x, uint256 y) {
        if (n == 0) return (uint256(1) << 224, uint256(1) << 224);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(add(cache, 32), mul(sub(add(offset, n), 5), 96)) }
        uint256 low0;
        uint256 rev0;
        uint256 low1;
        uint256 rev1;
        unchecked {
            (low0, rev0) = _initial(ptr, current0 + (0x78000001 - 1));
            (low1, rev1) = _initial(ptr, current1 + (0x78000001 - 1));
            assembly ("memory-safe") {
                for { let i := sub(n, 1) } i { i := sub(i, 1) } {
                    ptr := sub(ptr, 96)
                    current0 := mulmod(current0, current0, 0x78000001)
                    {
                        let M := 0x78000001
                        let bLow := mload(ptr)
                        let c4 :=
                            add(
                                shr(192, mul(low0, mload(add(ptr, 32)))),
                                mul(and(rev0, 0xffffffff), and(bLow, 0xffffffff))
                            )
                        let convLow := mul(low0, bLow)
                        let high := mul(rev0, mload(add(ptr, 64)))
                        let c0 := and(convLow, 0xffffffffffffffff)
                        let c1 := and(shr(64, convLow), 0xffffffffffffffff)
                        let c2 := and(shr(128, convLow), 0xffffffffffffffff)
                        let c3 := shr(192, convLow)
                        let c5 := shr(192, high)
                        let c6 := and(shr(128, high), 0xffffffffffffffff)
                        let c7 := and(shr(64, high), 0xffffffffffffffff)
                        let c8 := and(high, 0xffffffffffffffff)
                        let o0 :=
                            mod(
                                add(
                                    and(low0, 0xffffffff),
                                    mul(add(current0, 0x78000000), add(c0, shl(1, c5)))
                                ),
                                M
                            )
                        let o1 :=
                            mod(
                                add(
                                    and(shr(64, low0), 0xffffffff),
                                    mul(add(current0, 0x78000000), add(c1, shl(1, c6)))
                                ),
                                M
                            )
                        let o2 :=
                            mod(
                                add(
                                    and(shr(128, low0), 0xffffffff),
                                    mul(add(current0, 0x78000000), add(c2, shl(1, c7)))
                                ),
                                M
                            )
                        let o3 :=
                            mod(
                                add(
                                    shr(192, low0),
                                    mul(add(current0, 0x78000000), add(c3, shl(1, c8)))
                                ),
                                M
                            )
                        let o4 :=
                            mod(add(and(rev0, 0xffffffff), mul(add(current0, 0x78000000), c4)), M)
                        low0 := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
                        rev0 := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
                    }
                    current1 := mulmod(current1, current1, 0x78000001)
                    {
                        let M := 0x78000001
                        let bLow := mload(ptr)
                        let c4 :=
                            add(
                                shr(192, mul(low1, mload(add(ptr, 32)))),
                                mul(and(rev1, 0xffffffff), and(bLow, 0xffffffff))
                            )
                        let convLow := mul(low1, bLow)
                        let high := mul(rev1, mload(add(ptr, 64)))
                        let c0 := and(convLow, 0xffffffffffffffff)
                        let c1 := and(shr(64, convLow), 0xffffffffffffffff)
                        let c2 := and(shr(128, convLow), 0xffffffffffffffff)
                        let c3 := shr(192, convLow)
                        let c5 := shr(192, high)
                        let c6 := and(shr(128, high), 0xffffffffffffffff)
                        let c7 := and(shr(64, high), 0xffffffffffffffff)
                        let c8 := and(high, 0xffffffffffffffff)
                        let o0 :=
                            mod(
                                add(
                                    and(low1, 0xffffffff),
                                    mul(add(current1, 0x78000000), add(c0, shl(1, c5)))
                                ),
                                M
                            )
                        let o1 :=
                            mod(
                                add(
                                    and(shr(64, low1), 0xffffffff),
                                    mul(add(current1, 0x78000000), add(c1, shl(1, c6)))
                                ),
                                M
                            )
                        let o2 :=
                            mod(
                                add(
                                    and(shr(128, low1), 0xffffffff),
                                    mul(add(current1, 0x78000000), add(c2, shl(1, c7)))
                                ),
                                M
                            )
                        let o3 :=
                            mod(
                                add(
                                    shr(192, low1),
                                    mul(add(current1, 0x78000000), add(c3, shl(1, c8)))
                                ),
                                M
                            )
                        let o4 :=
                            mod(add(and(rev1, 0xffffffff), mul(add(current1, 0x78000000), c4)), M)
                        low1 := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
                        rev1 := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
                    }
                }
            }
        }
        return (_pack(low0, rev0), _pack(low1, rev1));
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }
}

contract BabyBearSelectAssemblyLoopHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        (x, y) = BabyBearSelectAssemblyLoop._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        return BabyBearSelectAssemblyLoop._selectPolyEvalFixed(
            a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectPrepackedCombined.prepare(point);
        result[0] = BabyBearSelectAssemblyLoop._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectAssemblyLoop._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectAssemblyLoop._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectCubics {
    function _multiply(uint256 aLow, uint256 aRev, uint256 bLow, uint256 bRev)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let c4 :=
                add(
                    shr(192, mul(aLow, or(shr(64, bLow), shl(192, and(bRev, 0xffffffff))))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, bRev)
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(c0, shl(1, c5)), M)
            let o1 := mod(add(c1, shl(1, c6)), M)
            let o2 := mod(add(c2, shl(1, c7)), M)
            let o3 := mod(add(c3, shl(1, c8)), M)
            let o4 := mod(c4, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(uint256 current, uint256[] memory cache, uint256, uint256 n)
        internal
        pure
        returns (uint256)
    {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(cache, 1312) }
        (uint256 low, uint256 rev, uint256 next) = _factor(ptr, current);
        unchecked {
            for (uint256 i = n / 2 - 1; i > 0; --i) {
                ptr -= 160;
                uint256 bLow;
                uint256 bRev;
                (bLow, bRev, next) = _factor(ptr, next);
                (low, rev) = _multiply(low, rev, bLow, bRev);
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 a,
        uint256 b,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256, uint256) {
        return (
            _selectPolyEvalFixed(a, cache, offset, n), _selectPolyEvalFixed(b, cache, offset, n)
        );
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearBenchField.mul(total, challenge), weight);
    }

    function _factor(uint256 ptr, uint256 x)
        private
        pure
        returns (uint256 lowOut, uint256 revOut, uint256 next)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let x2 := mulmod(x, x, M)
            let x3 := mulmod(x2, x, M)
            next := mulmod(x2, x2, M)
            let low :=
                add(
                    add(mload(ptr), mul(mload(add(ptr, 32)), x)),
                    add(mul(mload(add(ptr, 64)), x2), mul(mload(add(ptr, 96)), x3))
                )
            let last :=
                shr(
                    192,
                    mul(mload(add(ptr, 128)), or(or(x3, shl(64, x2)), or(shl(128, x), shl(192, 1))))
                )
            let o0 := mod(and(low, 0xffffffffffffffff), M)
            let o1 := mod(and(shr(64, low), 0xffffffffffffffff), M)
            let o2 := mod(and(shr(128, low), 0xffffffffffffffff), M)
            let o3 := mod(shr(192, low), M)
            let o4 := mod(last, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function prepare(uint256[] memory point) internal pure returns (uint256[] memory cache) {
        cache = new uint256[](45);
        for (uint256 i; i < 9; ++i) {
            uint256 r = point[2 * i + 5];
            uint256 s = point[2 * i + 4];
            uint256 d = BabyBearBenchField.mul(r, s);
            uint256 b = BabyBearBenchField.sub(r, d);
            uint256 cc = BabyBearBenchField.sub(s, d);
            uint256 a = BabyBearBenchField.add(
                BabyBearBenchField.sub(BabyBearBenchField.sub(uint256(1) << 224, r), s), d
            );
            uint256 ptr;
            assembly ("memory-safe") { ptr := add(add(cache, 32), mul(i, 160)) }
            _storeLow(ptr, a);
            _storeLow(ptr + 32, b);
            _storeLow(ptr + 64, cc);
            _storeLow(ptr + 96, d);
            assembly ("memory-safe") {
                mstore(
                    add(ptr, 128),
                    or(
                        or(and(shr(96, a), 0xffffffff), shl(64, and(shr(96, b), 0xffffffff))),
                        or(
                            shl(128, and(shr(96, cc), 0xffffffff)),
                            shl(192, and(shr(96, d), 0xffffffff))
                        )
                    )
                )
            }
        }
    }

    function _storeLow(uint256 ptr, uint256 b) private pure {
        assembly ("memory-safe") {
            mstore(
                ptr,
                or(
                    or(shr(224, b), shl(64, and(shr(192, b), 0xffffffff))),
                    or(
                        shl(128, and(shr(160, b), 0xffffffff)),
                        shl(192, and(shr(128, b), 0xffffffff))
                    )
                )
            )
        }
    }
}

contract BabyBearSelectCubicsHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        if (n % 2 != 0 || offset + n != 22) {
            uint256 t = gasleft();
            (x, y) = BabyBearSelectForms._selectPolyEvalFixedPair(
                a, b, BabyBearSelectPrepackedCombined.prepare(point), offset, n
            );
            return (t - gasleft(), x, y);
        }
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectCubics.prepare(point);
        (x, y) = BabyBearSelectCubics._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        if (n % 2 != 0 || offset + n != 22) {
            return BabyBearSelectForms._selectPolyEvalFixed(
                a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
            );
        }
        return BabyBearSelectCubics._selectPolyEvalFixed(
            a, BabyBearSelectCubics.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectCubics.prepare(point);
        result[0] = BabyBearSelectCubics._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectCubics._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectCubics._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

import { KoalaBearSelectForms } from "./BabyBearSelectForms.sol";

library KoalaBearSelectCubics {
    function _multiply(uint256 aLow, uint256 aRev, uint256 bLow, uint256 bRev)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let c4 :=
                add(
                    shr(192, mul(aLow, or(shr(64, bLow), shl(192, and(bRev, 0xffffffff))))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, bRev)
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let bias := shl(40, M)
            let o0 := mod(add(add(c0, c5), sub(bias, c8)), M)
            let o1 := mod(add(c1, c6), M)
            let o2 := mod(add(add(add(c2, sub(bias, c5)), c7), c8), M)
            let o3 := mod(add(add(c3, sub(bias, c6)), c8), M)
            let o4 := mod(add(c4, sub(bias, c7)), M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(uint256 current, uint256[] memory cache, uint256, uint256 n)
        internal
        pure
        returns (uint256)
    {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(cache, 1312) }
        (uint256 low, uint256 rev, uint256 next) = _factor(ptr, current);
        unchecked {
            for (uint256 i = n / 2 - 1; i > 0; --i) {
                ptr -= 160;
                uint256 bLow;
                uint256 bRev;
                (bLow, bRev, next) = _factor(ptr, next);
                (low, rev) = _multiply(low, rev, bLow, bRev);
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 a,
        uint256 b,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256, uint256) {
        return (
            _selectPolyEvalFixed(a, cache, offset, n), _selectPolyEvalFixed(b, cache, offset, n)
        );
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return KoalaBearExt5.add(KoalaBearExt5.mul(total, challenge), weight);
    }

    function _factor(uint256 ptr, uint256 x)
        private
        pure
        returns (uint256 lowOut, uint256 revOut, uint256 next)
    {
        assembly ("memory-safe") {
            let M := 0x7f000001
            let x2 := mulmod(x, x, M)
            let x3 := mulmod(x2, x, M)
            next := mulmod(x2, x2, M)
            let low :=
                add(
                    add(mload(ptr), mul(mload(add(ptr, 32)), x)),
                    add(mul(mload(add(ptr, 64)), x2), mul(mload(add(ptr, 96)), x3))
                )
            let last :=
                shr(
                    192,
                    mul(mload(add(ptr, 128)), or(or(x3, shl(64, x2)), or(shl(128, x), shl(192, 1))))
                )
            let o0 := mod(and(low, 0xffffffffffffffff), M)
            let o1 := mod(and(shr(64, low), 0xffffffffffffffff), M)
            let o2 := mod(and(shr(128, low), 0xffffffffffffffff), M)
            let o3 := mod(shr(192, low), M)
            let o4 := mod(last, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function prepare(uint256[] memory point) internal pure returns (uint256[] memory cache) {
        cache = new uint256[](45);
        for (uint256 i; i < 9; ++i) {
            uint256 r = point[2 * i + 5];
            uint256 s = point[2 * i + 4];
            uint256 d = KoalaBearExt5.mul(r, s);
            uint256 b = KoalaBearExt5.sub(r, d);
            uint256 cc = KoalaBearExt5.sub(s, d);
            uint256 a =
                KoalaBearExt5.add(KoalaBearExt5.sub(KoalaBearExt5.sub(uint256(1) << 224, r), s), d);
            uint256 ptr;
            assembly ("memory-safe") { ptr := add(add(cache, 32), mul(i, 160)) }
            _storeLow(ptr, a);
            _storeLow(ptr + 32, b);
            _storeLow(ptr + 64, cc);
            _storeLow(ptr + 96, d);
            assembly ("memory-safe") {
                mstore(
                    add(ptr, 128),
                    or(
                        or(and(shr(96, a), 0xffffffff), shl(64, and(shr(96, b), 0xffffffff))),
                        or(
                            shl(128, and(shr(96, cc), 0xffffffff)),
                            shl(192, and(shr(96, d), 0xffffffff))
                        )
                    )
                )
            }
        }
    }

    function _storeLow(uint256 ptr, uint256 b) private pure {
        assembly ("memory-safe") {
            mstore(
                ptr,
                or(
                    or(shr(224, b), shl(64, and(shr(192, b), 0xffffffff))),
                    or(
                        shl(128, and(shr(160, b), 0xffffffff)),
                        shl(192, and(shr(128, b), 0xffffffff))
                    )
                )
            )
        }
    }
}

contract KoalaBearSelectCubicsHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        if (n % 2 != 0 || offset + n != 22) {
            uint256 t = gasleft();
            (x, y) = KoalaBearSelectForms._selectPolyEvalFixedPair(
                a, b, KoalaBearSelectPrepackedCombined.prepare(point), offset, n
            );
            return (t - gasleft(), x, y);
        }
        uint256 start = gasleft();
        uint256[] memory cache = KoalaBearSelectCubics.prepare(point);
        (x, y) = KoalaBearSelectCubics._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        if (n % 2 != 0 || offset + n != 22) {
            return KoalaBearSelectForms._selectPolyEvalFixed(
                a, KoalaBearSelectPrepackedCombined.prepare(point), offset, n
            );
        }
        return KoalaBearSelectCubics._selectPolyEvalFixed(
            a, KoalaBearSelectCubics.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = KoalaBearSelectCubics.prepare(point);
        result[0] = KoalaBearSelectCubics._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = KoalaBearSelectCubics._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = KoalaBearSelectCubics._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

library BabyBearSelectCubicsPackedHorner {
    function _multiply(uint256 aLow, uint256 aRev, uint256 bLow, uint256 bRev)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let c4 :=
                add(
                    shr(192, mul(aLow, or(shr(64, bLow), shl(192, and(bRev, 0xffffffff))))),
                    mul(and(aRev, 0xffffffff), and(bLow, 0xffffffff))
                )
            let low := mul(aLow, bLow)
            let high := mul(aRev, bRev)
            let c0 := and(low, 0xffffffffffffffff)
            let c1 := and(shr(64, low), 0xffffffffffffffff)
            let c2 := and(shr(128, low), 0xffffffffffffffff)
            let c3 := shr(192, low)
            let c5 := shr(192, high)
            let c6 := and(shr(128, high), 0xffffffffffffffff)
            let c7 := and(shr(64, high), 0xffffffffffffffff)
            let c8 := and(high, 0xffffffffffffffff)
            let o0 := mod(add(c0, shl(1, c5)), M)
            let o1 := mod(add(c1, shl(1, c6)), M)
            let o2 := mod(add(c2, shl(1, c7)), M)
            let o3 := mod(add(c3, shl(1, c8)), M)
            let o4 := mod(c4, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _initial(uint256 ptr, uint256 scalar)
        private
        pure
        returns (uint256 lowOut, uint256 revOut)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let b := mload(ptr)
            let o0 := mod(add(1, mul(and(b, 0xffffffff), scalar)), M)
            let o1 := mulmod(and(shr(64, b), 0xffffffff), scalar, M)
            let o2 := mulmod(and(shr(128, b), 0xffffffff), scalar, M)
            let o3 := mulmod(shr(192, b), scalar, M)
            let o4 := mulmod(shr(192, mload(add(ptr, 32))), scalar, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function _pack(uint256 low, uint256 rev) private pure returns (uint256 out) {
        assembly ("memory-safe") {
            out := or(
                or(
                    or(shl(224, and(low, 0xffffffff)), shl(192, and(shr(64, low), 0xffffffff))),
                    or(shl(160, and(shr(128, low), 0xffffffff)), shl(128, shr(192, low)))
                ),
                shl(96, and(rev, 0xffffffff))
            )
        }
    }

    function _selectPolyEvalFixed(uint256 current, uint256[] memory cache, uint256, uint256 n)
        internal
        pure
        returns (uint256)
    {
        if (n == 0) return uint256(1) << 224;
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(cache, 1312) }
        (uint256 low, uint256 rev, uint256 next) = _factor(ptr, current);
        unchecked {
            for (uint256 i = n / 2 - 1; i > 0; --i) {
                ptr -= 160;
                uint256 bLow;
                uint256 bRev;
                (bLow, bRev, next) = _factor(ptr, next);
                (low, rev) = _multiply(low, rev, bLow, bRev);
            }
        }
        return _pack(low, rev);
    }

    function _selectPolyEvalFixedPair(
        uint256 a,
        uint256 b,
        uint256[] memory cache,
        uint256 offset,
        uint256 n
    ) internal pure returns (uint256, uint256) {
        return (
            _selectPolyEvalFixed(a, cache, offset, n), _selectPolyEvalFixed(b, cache, offset, n)
        );
    }

    function _evaluateConstraintSelectRaw18WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 4, 18);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 4, 18)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw14WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 8, 14);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 8, 14)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _evaluateConstraintSelectRaw10WithPrecomputedEq(
        uint256 challenge,
        uint256 eqEval,
        uint256[] memory selVars,
        uint256[] memory fullPoint
    ) internal pure returns (uint256 total) {
        unchecked {
            uint256 i = selVars.length;
            for (; i > 1;) {
                uint256 eval0;
                uint256 eval1;
                (eval0, eval1) =
                    _selectPolyEvalFixedPair(selVars[i - 1], selVars[i - 2], fullPoint, 12, 10);
                total = _hornerStep(total, challenge, eval0);
                total = _hornerStep(total, challenge, eval1);
                i -= 2;
            }
            if (i != 0) {
                total = _hornerStep(
                    total, challenge, _selectPolyEvalFixed(selVars[0], fullPoint, 12, 10)
                );
            }
        }
        total = _hornerStep(total, challenge, eqEval);
    }

    function _hornerStep(uint256 total, uint256 challenge, uint256 weight)
        internal
        pure
        returns (uint256)
    {
        return BabyBearBenchField.add(BabyBearPackedField.mul(total, challenge), weight);
    }

    function _factor(uint256 ptr, uint256 x)
        private
        pure
        returns (uint256 lowOut, uint256 revOut, uint256 next)
    {
        assembly ("memory-safe") {
            let M := 0x78000001
            let x2 := mulmod(x, x, M)
            let x3 := mulmod(x2, x, M)
            next := mulmod(x2, x2, M)
            let low :=
                add(
                    add(mload(ptr), mul(mload(add(ptr, 32)), x)),
                    add(mul(mload(add(ptr, 64)), x2), mul(mload(add(ptr, 96)), x3))
                )
            let last :=
                shr(
                    192,
                    mul(mload(add(ptr, 128)), or(or(x3, shl(64, x2)), or(shl(128, x), shl(192, 1))))
                )
            let o0 := mod(and(low, 0xffffffffffffffff), M)
            let o1 := mod(and(shr(64, low), 0xffffffffffffffff), M)
            let o2 := mod(and(shr(128, low), 0xffffffffffffffff), M)
            let o3 := mod(shr(192, low), M)
            let o4 := mod(last, M)
            lowOut := or(or(o0, shl(64, o1)), or(shl(128, o2), shl(192, o3)))
            revOut := or(or(o4, shl(64, o3)), or(shl(128, o2), shl(192, o1)))
        }
    }

    function prepare(uint256[] memory point) internal pure returns (uint256[] memory cache) {
        cache = new uint256[](45);
        for (uint256 i; i < 9; ++i) {
            uint256 r = point[2 * i + 5];
            uint256 s = point[2 * i + 4];
            uint256 d = BabyBearBenchField.mul(r, s);
            uint256 b = BabyBearBenchField.sub(r, d);
            uint256 cc = BabyBearBenchField.sub(s, d);
            uint256 a = BabyBearBenchField.add(
                BabyBearBenchField.sub(BabyBearBenchField.sub(uint256(1) << 224, r), s), d
            );
            uint256 ptr;
            assembly ("memory-safe") { ptr := add(add(cache, 32), mul(i, 160)) }
            _storeLow(ptr, a);
            _storeLow(ptr + 32, b);
            _storeLow(ptr + 64, cc);
            _storeLow(ptr + 96, d);
            assembly ("memory-safe") {
                mstore(
                    add(ptr, 128),
                    or(
                        or(and(shr(96, a), 0xffffffff), shl(64, and(shr(96, b), 0xffffffff))),
                        or(
                            shl(128, and(shr(96, cc), 0xffffffff)),
                            shl(192, and(shr(96, d), 0xffffffff))
                        )
                    )
                )
            }
        }
    }

    function _storeLow(uint256 ptr, uint256 b) private pure {
        assembly ("memory-safe") {
            mstore(
                ptr,
                or(
                    or(shr(224, b), shl(64, and(shr(192, b), 0xffffffff))),
                    or(
                        shl(128, and(shr(160, b), 0xffffffff)),
                        shl(192, and(shr(128, b), 0xffffffff))
                    )
                )
            )
        }
    }
}

contract BabyBearSelectCubicsPackedHornerHarness {
    function chains(uint256[] memory point, uint256 a, uint256 b, uint256 offset, uint256 n)
        external
        view
        returns (uint256 used, uint256 x, uint256 y)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        if (n % 2 != 0 || offset + n != 22) {
            uint256 t = gasleft();
            (x, y) = BabyBearSelectForms._selectPolyEvalFixedPair(
                a, b, BabyBearSelectPrepackedCombined.prepare(point), offset, n
            );
            return (t - gasleft(), x, y);
        }
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectCubicsPackedHorner.prepare(point);
        (x, y) = BabyBearSelectCubicsPackedHorner._selectPolyEvalFixedPair(a, b, cache, offset, n);
        used = start - gasleft();
    }

    function single(uint256[] memory point, uint256 a, uint256 offset, uint256 n)
        external
        pure
        returns (uint256)
    {
        require(point.length == 22 && offset >= 4 && offset <= 22 && n <= 22 - offset, "SHAPE");
        if (n % 2 != 0 || offset + n != 22) {
            return BabyBearSelectForms._selectPolyEvalFixed(
                a, BabyBearSelectPrepackedCombined.prepare(point), offset, n
            );
        }
        return BabyBearSelectCubicsPackedHorner._selectPolyEvalFixed(
            a, BabyBearSelectCubicsPackedHorner.prepare(point), offset, n
        );
    }

    function batch(
        uint256[] memory point,
        uint256[][3] memory selectors,
        uint256[3] memory challenges,
        uint256[3] memory eqs
    ) external view returns (uint256 used, uint256[3] memory result) {
        require(
            point.length == 22 && selectors[0].length == 38 && selectors[1].length == 31
                && selectors[2].length == 19,
            "SHAPE"
        );
        uint256 start = gasleft();
        uint256[] memory cache = BabyBearSelectCubicsPackedHorner.prepare(point);
        result[0] = BabyBearSelectCubicsPackedHorner._evaluateConstraintSelectRaw18WithPrecomputedEq(
            challenges[0], eqs[0], selectors[0], cache
        );
        result[1] = BabyBearSelectCubicsPackedHorner._evaluateConstraintSelectRaw14WithPrecomputedEq(
            challenges[1], eqs[1], selectors[1], cache
        );
        result[2] = BabyBearSelectCubicsPackedHorner._evaluateConstraintSelectRaw10WithPrecomputedEq(
            challenges[2], eqs[2], selectors[2], cache
        );
        used = start - gasleft();
    }
}

